### ISSUE TITLE
レンダリングされているコンテンツ (content rendering)の見直し

### ISSUE THREAD

**Issue by momdo** [waic/atag20-ja#109]
https://github.com/waic/atag20-ja/pull/105#discussion_r271773262 より
とくに https://waic.github.io/atag20-ja/#def-WYSIWYG について
- conventionalを「標準」と取っていいものなのか
- これも後ででいいのですが、「What-you-see-is-what-you-get (見えているものが得るもの) 」という訳でいいのかどうか
- orの見直し「また」→「又は」

**Comment by motchie** [comment]
# 原文:
**conventional renderings (or "WYSIWYG"):** When content is rendered in a way that is similar to the default rendering a user agent would create from the same content. While "WYSIWYG", standing for "What-you-see-is-what-you-get" is the common term, differences between user agents and end user settings mean that in reality there is no single typical end user experience; or
# 現訳文:
**標準レンダリング (又は「WYSIWYG」)(conventional renderings (or "WYSIWYG")):** コンテンツが、ユーザエージェントが同じコンテンツを初期設定のままレンダリングする方法と似た方法でレンダリングされる場合。「WYSIWYG」は、「What-you-see-is-what-you-get (見えているものが得るもの) 」を意味する一般的な言葉だが、ユーザエージェントとエンドユーザの設定の違いによって、エンドユーザの体験は典型的なものにはならないことを意味する。また、

**Comment by motchie** [comment]
訳出案です。

** (又は「WYSIWYG」)(conventional renderings (or "WYSIWYG")):** コンテンツが、ユーザエージェントが同じコンテンツを初期設定のままレンダリングする方法と似た方法でレンダリングされる場合。「WYSIWYG」は、「What-you-see-is-what-you-get () 」を意味する一般的な言葉だが、ユーザエージェントとエンドユーザの設定の違いによって、エンドユーザの体験は典型的なものにはならないことを意味する。また、

**Comment by motchie** [comment]
あー、WYSIWYG だけちゃうのか、これー。
