### ISSUE TITLE
「プレビュー専用」の見直し

### ISSUE THREAD

**Issue by momdo** [waic/atag20-ja#111]
https://github.com/waic/atag20-ja/pull/105#discussion_r271784728 より

https://waic.github.io/atag20-ja/#def-User-Agent

「プレビュー専用」の訳が微妙に変。

>If the user agent functionality must retrieve and open web content before it can be sent to the authoring tool functionality, then the software is a user agent with an authoring tool mode. If the user agent is used to preview content produced by the authoring tool mode, then it is to be considered an in-market user agent.

少なくとも、
- オープンする必要がある←must retrieve and openなので、「～しなければならない」とするべき
- 市場のユーザエージェントと見なされるべきである。← it is to be consideredなので、こう取っても誤りではないのですが、shouldではないのでかぶってしまうのが懸念事項

といったところ。

**Comment by caztcha** [comment]
PR #146 にて対応中です。

**Comment by momdo** [comment]
マージ済みなのでcloseします。
