### ISSUE TITLE
「コンテンツ変換」の見直し

### ISSUE THREAD

**Issue by momdo** [waic/atag20-ja#112]
https://github.com/waic/atag20-ja/pull/105#discussion_r271788067 より

https://waic.github.io/atag20-ja/#def-Transformation

「(例えば～など)」というフレーズが3つそれぞれに出現するが、どれも訳出の仕方が微妙に異なる（読点があったりなかったり、「～たり…たり」の呼応なのか、「～や…。」と単にするのか）ので統一する。

**Comment by caztcha** [comment]
PR #142 にて対応中です。

**Comment by momdo** [comment]
マージしたのでCloseします。
