### ISSUE TITLE
「1つ又は複数」というフレーズ

### ISSUE THREAD

**Issue by momdo** [waic/atag20-ja#116]
「一つ以上」が適当では？

**Comment by bakera** [comment]
WCAG本体訳ではone or more は「一つ以上」としています。

https://www.w3.org/TR/2008/REC-WCAG20-20081211/#sectiondef
https://waic.jp/docs/WCAG20/Overview.html#sectiondef

**Comment by motchie** [comment]
> ありがとうございます。
> コミット自体は問題ないのですが、「一つ又は複数の」という言い方が若干不自然かなと。
> ついでに「一つ以上の」にしてしましょう…！

https://github.com/waic/atag20-ja/pull/125#pullrequestreview-245791088

で解消していると思われます。現時点でのmasterブランチに、該当フレーズが検索でヒットしません。
クローズします。
