### ISSUE TITLE
A.2.1.2(b) 翻訳の見直し

### ISSUE THREAD

**Issue by momdo** [waic/atag20-ja#117]
https://www.w3.org/TR/2015/REC-ATAG20-20150924/#gl_a21
> (b) User Agent Option: Authors have the option to preview the time-based media in a user agent that is able to render the alternatives.

https://waic.github.io/atag20-ja/#gl_a21
> (b) ユーザエージェントのオプション: コンテンツ制作者はユーザエージェントのオプションによって、時間依存メディアの代替コンテンツをプレビューすることができる。

述語動詞はhaveなので、「コンテンツ制作者は、…オプションを持つ。」のようにすべきでは。直前の

> (a) レンダリングのオプション: オーサリングツールは時間依存メディアの代替コンテンツをレンダリングするオプションを提供する。または、

と対比するような訳のほうが都合がよさそうな。

**Comment by bakera** [comment]
実はその見出し部分が、

(a) Option to Render:
(a) レンダリングのオプション:

(b) User Agent Option:
(b) ユーザエージェントのオプション:

となっていて、原文では対比になっていないのに対比的に訳されていますね。
