### ISSUE TITLE
(最低限レベル)と(最低限)が混在している

### ISSUE THREAD

**Issue by momdo** [waic/atag20-ja#118]
A.3.1.1 キーボードアクセス（最低限レベル）
A.3.2.1 自動保存（最低限レベル）
A.3.7.1 プレビュー（最低限レベル）
A.4.1.1 コンテンツ変更の可逆性（最低限）

A.3.1.1 Keyboard Access (Minimum)
A.3.2.1 Auto-Save (Minimum)
A.3.7.1 Preview (Minimum)
A.4.1.1 Content Changes Reversible (Minimum)

どちらかに統一する

**Comment by bakera** [comment]
WCAG 2.0やJISでは「コントラスト (最低限) 」などとしていますので、「 (最低限) 」のほうに統一でお願いしたいです。
