### ISSUE TITLE
本編パートA翻訳

### ISSUE THREAD

**Issue by bakera** [waic/atag20-ja#13]

**Comment by bakera** [comment]
PR #8 にてレビュー中

**Comment by MasaoYOMODA** [comment]
@bakera @honoka-h PR #8 確認しました。内容OKです。ご連絡遅れ失礼しました。
後は（ミスを避けたいので）会合の場で確認しながら操作、とさせてください。よろしくお願いします。

**Comment by momdo** [comment]
マージされたのでクローズします。
