### ISSUE TITLE
本編パートB翻訳

### ISSUE THREAD

**Issue by bakera** [waic/atag20-ja#14]

**Comment by caztcha** [comment]
@yoota 吉村さんによる翻訳作業が完了しており、土屋のレビューを実施するステータスなので、ラベルを「翻訳作業中」→「レビュー中」に変更しました。

**Comment by caztcha** [comment]
@imagedrive レビュー完了しました。
PR [#20](https://github.com/waic/atag20-ja/pull/20) にコメントを入れてあります。
ご確認よろしくお願いします。

**Comment by caztcha** [comment]
@cocktailz さんにご対応いただきました。
以後、PR [#22](https://github.com/waic/atag20-ja/pull/22/) での扱いになります。

PR [#20](https://github.com/waic/atag20-ja/pull/20/) についてはクローズしてもよいかなと思います。
@bakera いかがでしょうか？

**Comment by bakera** [comment]
#22は#20のブランチに対するプルリクエストになっていますので、まず#22をマージして、そのあとで#20をmasterにマージするのが良いかと思います。

**Comment by cocktailz** [comment]
遅くなりました。PR #22 のコメント反映しました。ご確認いただけますでしょうか。
https://github.com/waic/atag20-ja/commit/d15ac704cfebc96c1a6414a87f667730ceae4f64
