### ISSUE TITLE
and encouragedの訳に違和感

### ISSUE THREAD

**Issue by 8845musign** [waic/atag20-ja#141]
**B.3.1.1 チェックの補助 (WCAG)** 
原文：
> Note: Automated and semi-automated checking is possible (and encouraged) for many types of web content accessibility problems (WCAG).

訳：
> 注記: 自動及び半自動チェックは、多くの種類のウェブコンテンツのアクセシビリティ問題 (WCAG) が起こりうる (また促す)。

**B.3.2.1 修正支援(WCAG)**
原文：
> Note: Automated and semi-automated repair is possible (and encouraged) for many types of web content accessibility problems (WCAG).

訳：
> 注記: 自動修正や自動チェック、半自動修正では多くのウェブコンテンツのアクセシビリティ問題 (WCAG) が起こりうる (または促す)。

`and encouraged` ですが、 `and` が `or` として訳されている気がします。
「及び促す」としたほうが良いでしょうか。

**Comment by bakera** [comment]
全体が誤訳という説が浮上しました。
「ウェブコンテンツのアクセシビリティ問題 (WCAG) 」はこれで一単語なのでそこはOK
たとえばこんな訳で:
注記: 多くの種類のウェブコンテンツのアクセシビリティ問題 (WCAG) に対して、自動及び半自動チェックが可能である (そして推奨される)。

**Comment by bakera** [comment]
B.3.2.1 にも似た文で check が repair になっているだけのものがあるので、そちらもあわせて修正の必要があります。

**Comment by 8845musign** [comment]
今内容確認していますが。

> B.3.1.1 チェックの補助 (WCAG)

については @caztcha さんにご対応いただいてるみたいですね、ありがとうございます👏

> B.3.2.1 修正支援(WCAG)

のみ対応いたします。

**Comment by 8845musign** [comment]
https://www.w3.org/TR/ATAG20/#sc_b321

B.3.2.1 の原文、「Automated and semi-automated」の「and」に対してautomated checkingへリンクがはられていますが、ミスですかネ……。

リンク外しておきます。

**Comment by momdo** [comment]
マージ済みなのでcloseします。

**Comment by 8845musign** [comment]
「Automated」について B.3.1.1 と B.3.2.1 で訳がズレているので再オープンいたしました。  
修正候補を https://github.com/waic/atag20-ja/pull/148 にて提案しておりますのでご確認お願いいたします。

**Comment by momdo** [comment]
マージ済みなので再度closeします。
