### ISSUE TITLE
ATAG 2.0翻訳更新版の公開準備

### ISSUE THREAD

**Issue by momdo** [waic/atag20-ja#147]
- [x] GitHubでリリースタグをつけて、ファイルを固める
- [x] ステージング環境にアップロードを依頼する
- [x] WAICメーリングリストでWAIC内レビューを依頼する（レビュー期間2週間）
- [x] レビューコメントがあれば対応する
- [ ] 本番環境で公開を依頼する
- [ ] WAICサイトに掲載するニュースの文面を確定させる

Googleフォームへの問い合わせリンクは対応済み。

**Comment by momdo** [comment]
https://github.com/waic/atag20-ja/releases/tag/2020-04 としてリリースタグ発行

**Comment by momdo** [comment]
- ステージング環境に依頼済み（更新済み）
- WAIC MLにて依頼済み、レビュー期限は4/13（月）〆

**Comment by bakera** [comment]
ちょっと忘れていましたがレビュー期間が終わっていて、特にコメントはきていないようです。

**Comment by momdo** [comment]
主査・副査の環境へのアクセス権限と方法を調整中。
終わり次第公開予定。

また、文面案はSlackに記入済み。

**Comment by momdo** [comment]
Authoring Tool Accessibility Guidelines (ATAG) 2.0 の日本語訳を更新しました | ウェブアクセシビリティ基盤委員会（WAIC）
https://waic.jp/news/20200511-2/
🎉
