### ISSUE TITLE
「クローズドコンテナ」訳語検討

### ISSUE THREAD

**Issue by bakera** [waic/atag20-ja#24]
closed containerを「クローズドコンテナ」としているが、何なのか直感的にわかりにくいという意見があった。全体の訳が出そろったところで検討する。

**Comment by bakera** [comment]
「クローズドコンテナ」というものがあるのではなく、コンテナが開いている場合と閉じている場合、という話で出てくる言葉のよう。
いったん「閉じられたコンテナ」とするのが良いのではないか。

**Comment by caztcha** [comment]
@bakera 機械的な修正なので、issue #25 と併せて、私の方で作業しましょうか？

**Comment by bakera** [comment]
ありがとうございます。お願いします!

**Comment by caztcha** [comment]
[PR #30](https://github.com/waic/atag20-ja/pull/30) にて対応しました。よろしければマージお願いします！
