### ISSUE TITLE
表記ゆれの一括置換

### ISSUE THREAD

**Issue by caztcha** [waic/atag20-ja#25]
s/ユーザー/ユーザ/
s/インターフェース/インタフェース/

... what else?

念のため、ひととおり翻訳が出揃ったところで、ATAG 2.0 全体で一括検索/置換するのがよさそうです。

**Comment by bakera** [comment]
「注」「注記」の揺れもあるので一緒に対応。
目についたものがあればやる方針で。

**Comment by caztcha** [comment]
「注」と「注記」の表記ゆれも同時に修正する。

**Comment by caztcha** [comment]
Line 1380, Column 190: start tag was here
>…AG 2.0 はウェブコンテンツ技術を<em>アクセシビリティ サポーテッド<em>であるとみなす。

em 要素の閉じタグが閉じタグになっていないのを修正する。

**Comment by caztcha** [comment]
1781行めにもddタグがある（重複している、いらない）
1774行めに謎のbrの終了タグがある (/br)

**Comment by momdo** [comment]
@caztcha いちおう、マークアップの話題は #28 にも書いておきました。

**Comment by caztcha** [comment]
[PR #31](https://github.com/waic/atag20-ja/pull/31) にて対応しました。よろしければマージお願いします！

**Comment by caztcha** [comment]
@bakera マージありがとうございました。
その後、「注」→「注記」の置換漏れがあり、追加で [PR #33](https://github.com/waic/atag20-ja/pull/33) を立て、土屋の方でマージさせていただきました。

https://waic.github.io/atag20-ja/
にひととおりマージが反映されていることを確認しましたので、本件、クローズさせていただきます。
