### ISSUE TITLE
用語集における原文併記の統一

### ISSUE THREAD

**Issue by momdo** [waic/atag20-ja#27]
>目立つ度合い (prominence)
プロンプト

という具合に、かっこの併記がない。また、

>コンテンツ (ウェブコンテンツ) (content (web content))
(中略)
アクセシブルなコンテンツ (accessible content) (WCAG): 

>コンテンツ生成（コンテンツオーサリング、コンテンツ編集) (content generation (content authoring, content editing))
コンテンツ制作者が生成するコンテンツ

というように、用語の中の用語について、かっこのありなしが混在している。

**Comment by bakera** [comment]
かっこありに統一します!

**Comment by motchie** [comment]
`id="def-Authoring-Interface-Accessibility-Problem"` のように、`id` に `def-` が含まれてる箇所は「用語」または「用語中の用語」と解釈して進める。

**Comment by motchie** [comment]
原文が表記されていない用語については、日本語の用語の後に半角スペース、続けて半角カッコ `()` を加えて、この半角カッコ中に https://www.w3.org/TR/2015/REC-ATAG20-20150924/#glossary からの原文を追加する。

**Comment by motchie** [comment]
訳語に、すでに `(WCAG)` が付加されている場合、次のルールとする。
```訳出した用語 (原文の用語)(WCAG)```
`(原文の用語)` と `(WCAG)` の間にスペースは入れない。

**Comment by motchie** [comment]
https://github.com/waic/atag20-ja/pull/105 をマージしたので、こちらもクローズします。
