### ISSUE TITLE
Combined User Agent/Authoring Tool訳語の統一

### ISSUE THREAD

**Issue by bakera** [waic/atag20-ja#34]
イントロダクションの末尾に以下のようにありますが、

> User Agent Accessibility Guidelines (UAAG) Overview（これは「複合ユーザエージェント/オーサリングツール」および「オーサリングツールモードのユーザエージェント」の開発者にとって特に重要である）

「複合ユーザエージェント/オーサリングツール」は用語へのリンクになっています。

https://waic.github.io/atag20-ja/#def-comb-ua-authoring-tool

リンク先を見ると、こちらでは

>結合したユーザエージェント/オーサリングツール

となって訳語が揺れています。
なお、原文は Combined User Agent/Authoring Tool です。

**Comment by bakera** [comment]
説明を読む限りでは「統合」「統合された」のような訳語が良さそうに思えます。

**Comment by motchie** [comment]
念の為、原文を `grep` して出現箇所を確認。
