### ISSUE TITLE
フォーマットおよび表記揺れの修正

### ISSUE THREAD

**Issue by momdo** [waic/atag20-ja#35]
#31 で若干対応いただいたが、いくつか見つけたので修正する

- および→及び
- または→又は
- 全角括弧・全角コロンを半角にする
- 半角スペースの調整
- セミコロンを句読点に置換

**Comment by bakera** [comment]
ルールはあるので、それに沿って統一する方向で。

**Comment by momdo** [comment]
https://github.com/waic/atag20-ja/pull/105#discussion_r271789469 のような、either A or Bも考えておく。

**Comment by 8845musign** [comment]
@momdo @motchie
質問です。
「アクセシビリティ サポーテッド」、分かち書きのスペースは削除してよろしいでしょうか。

関連:

#101
#89

**Comment by 8845musign** [comment]
すみません、ガイドラインに記載あり問題ない表記でしたね…。
https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md#%E5%88%86%E3%81%8B%E3%81%A1%E6%9B%B8%E3%81%8Dg63

**Comment by momdo** [comment]
@8845musign ガイドラインがわかりにくくてごめんなさい…

**Comment by 8845musign** [comment]
@momdo 
とんでもないです、私の読み込み不足でした。

**Comment by 8845musign** [comment]
こちら作業完了しておりますのでクローズいたします。
