### ISSUE TITLE
表記揺れ

### ISSUE THREAD

**Issue by SawadaStdDesign** [waic/atag20-ja#40]
「アクセシビリティ問題」と「アクセシビリティの問題」
「障害のある人」と「障害を持つ人々」と「障害当事者」
「関連づけ」と「関連付け」
「時間ベース」と「時間依存」
「サポートする」と「支援する」
「少なくとも同程度目立つ」と「少なくとも顕在」
「順次キーボードアクセス」と「連続したキーボードアクセス」
「デザイナ」と「デザイナー」
「ドキュメント」と「ドキュメンテーション」
「プロンプト」と「要求」
「一つ」と「１つ」
「二つ」と「2つ」
「アクセシビリティ サポーテッド」と「アクセスサポーティッド」
「プラットフォームアクセシビリティサービス」と「プラットフォームのアクセシビリティサービス」

**Comment by bakera** [comment]
ありがとうございます。
子イシューが全部クローズされたらこのイシューを閉じましょう。

**Comment by momdo** [comment]
子課題がすべてCloseできたので、こちらもCloseします。

@motchie さんをはじめ、作業いただいたみなさんありがとうございました。
