### ISSUE TITLE
長いカタカナ訳

### ISSUE THREAD

**Issue by SawadaStdDesign** [waic/atag20-ja#45]
A.1.2.1
「ユーザインタフェースアクセシビリティガイドライン」は、途中にスペースを入れた方が読みやすくないでしょうか？

**Comment by bakera** [comment]
ひとまず以下は空ける方向で。
ユーザインタフェース アクセシビリティガイドライン
ユーザインタフェース コンポーネント
ユーザインタフェース ウィジェット
他に長いのが出てきたら都度相談します。

**Comment by caztcha** [comment]
@bakera PR [#58](https://github.com/waic/atag20-ja/pull/58) にて対応しました。

**Comment by momdo** [comment]
上記の3語については問題なさそうです。
その一方で、「オーサリングユーザインタフェース」という語が3カ所出現していますが、これについてはスペースなしの方向で大丈夫でしょうか…？

**Comment by caztcha** [comment]
@momdo ご指摘ありがとうございます。「ユーザインタフェース」の手前にカタカナ語が来る複合語については確認していませんでした。助かりました。
PR #58 に追加でプルリクエストをしました。 https://github.com/waic/atag20-ja/pull/58/commits/af95e6c18b215f28704336cca1ad823ba58183d2

**Comment by momdo** [comment]
マージされたので閉じます
