### ISSUE TITLE
リンクラベル違い（単語 提示 (presentation)について）

### ISSUE THREAD

**Issue by SawadaStdDesign** [waic/atag20-ja#47]
A.2.2:
用語集の「提示 (presentation)」へのリンク元の文言が「プレゼンテーション」になっています。

**Comment by bakera** [comment]
非常に根の深い問題ですね。
基本は「提示」なのですが、提示とすると違和感のある個所がありそうです。
動詞 present も含めて調査・検討する必要があります。

なお、用語「テンプレート」の中にある「プレゼンテーションのテーマ」は「プレゼンテーション」のままとします。

**Comment by momdo** [comment]
関連 waic/wcag20#33

**Comment by bakera** [comment]
WCAG 2.0側の対応をこちらにも反映で (つまり原則は「提示」とする)。
