### ISSUE TITLE
「ディスプレイ」について

### ISSUE THREAD

**Issue by SawadaStdDesign** [waic/atag20-ja#50]
A.3.6.1など
「ディスプレイの設定」は物理的なイメージが強い印象を受けますので「画面設定」などはいかがでしょうか？

**Comment by bakera** [comment]
見た目に限らず音声、触覚などのモダリティに関する設定も含む定義なので、「表示設定」としたいと思います。
ただし、audio display setting というものがあり、「音声表示設定」は違和感があるという意見がありました。実際違和感はあるのですが、英語でも違和感があるので違和感があるまま訳されれば良いのではないか、という意見も出ました。

**Comment by caztcha** [comment]
澤田さんにも確認します。

**Comment by SawadaStdDesign** [comment]
ご検討いただきましてありがとうございます！
A.3.6では、ウィンドウやツールパレットの環境設定についての内容でしょうから、「表示設定」で違和感はないですね。
当方としては、「ディスプレイ」というと「モニター」と同じくハードウェアの名称としても定着している呼び方のように感じましたので、そうではない言い回しができていて良いと思います。
「音声表示設定」に対する違和感は「音声の表示設定」とするだけでも軽減できるのではないでしょうか？

**Comment by caztcha** [comment]
@SawadaStdDesign ありがとうございます。「音声表示設定」or「音声の表示設定」については、他の案も含めて、PR #60 にて @momdo も交えて議論いただいているので、そこで検討したいと思います。

**Comment by momdo** [comment]
マージされたので閉じます
