### ISSUE TITLE
「at least one of the following is true」について

### ISSUE THREAD

**Issue by SawadaStdDesign** [waic/atag20-ja#51]
A.4.2.1など
「次のいずれかを少なくともひとつ満たす」は「次に挙げる事項のうち、少なくとも一つを満たしている」ではないでしょうか？

**Comment by bakera** [comment]
WCAG本体側がご指摘の表記なので、それにそろえる形で良いかと思います。

**Comment by caztcha** [comment]
PR [#92](https://github.com/waic/atag20-ja/pull/92) で対応しました。

**Comment by momdo** [comment]
マージされたので閉じます
