### ISSUE TITLE
「ウェブコンテンツアクセシビリティガイドライン (WCAG) 2.0 との関係」直下の文章

### ISSUE THREAD

**Issue by SawadaStdDesign** [waic/atag20-ja#52]
「〜サポートし、ガイドするか」で文章が終わっています。
次の段落
「「レベル A、AA、又は AAA のいずれかで」という語句は。」は「。」ではなく「、」ですね。

**Comment by motchie** [comment]
1. 「〜サポートし、ガイドするか」で文章が終わっています。

2. 「「レベル A、AA、又は AAA のいずれかで」という語句は。」は「。」ではなく「、」

**Comment by tokimari** [comment]
closed by #95
