### ISSUE TITLE
「アクセシビリティ問題」vs「アクセシビリティの問題」

### ISSUE THREAD

**Issue by bakera** [waic/atag20-ja#55]
#40 より
「アクセシビリティ問題」と「アクセシビリティの問題」

「反映されたコンテンツのアクセシビリティの問題」、「オーサリングツールのユーザインタフェースのアクセシビリティ問題」など多岐にわたり多数の箇所を検討する必要がある。
対象を洗い出して検討する作業が必要。

**Comment by momdo** [comment]
まずは、該当箇所を全部列挙するところから…。

**Comment by motchie** [comment]
# 「アクセシビリティ問題」(数字は行番号)
395:      <li><a name="part_a_applic_note_2" id="part_a_applic_note_2"></a><strong class="handle">反映されたコンテンツのアクセシビリティの問題:</strong> <a class="termdef" href="#def-Authoring-Tool" title="定義: オーサリングツール">オーサリングツール</a>は<a href="#def-Editing-View" title="定義: 編集ビュー" class="termdef">編集ビュー</a>に表示されている<a class="termdef" href="#def-Content-Being-Edited" title="定義: 編集中のウェブコンテンツ">編集中のウェブコンテンツ</a>が障害を持つ<a class="termdef" href="#def-Author" title="定義: コンテンツ制作者">コンテンツ制作者</a>にとってよりアクセシブルな方法で提供されていることを保証する責任がある (例: コンテンツの<span class="sc-bullet"><a class="termdef" href="#def-Text-Alternatives" title="非テキストコンテンツの代替テキスト">代替テキスト</a></span>が<a class="termdef" href="#def-Programmatically-Determined" title="定義: プログラムによる解釈可能">プログラムによる解釈可能</a>であることを保証する)。しかし、<a href="#def-Authoring-Interface-Accessibility-Problem" title="定義: オーサリングツールのユーザインタフェースの**アクセシビリティ問題**" class="termdef">オーサリングツールのユーザインタフェースの**アクセシビリティ問題**</a>が編集されているコンテンツによって発生している箇所 (例: コンテンツ内の画像にテキストによる代替が不足している場合) では、<a href="#def-Authoring-Tool-Interface" title="定義: オーサリングツールのユーザインタフェース" class="termdef">オーサリングツールのユーザインタフェース</a>のアクセシビリティが不足しているとは見なされない。<br/>
887:<p class="rationale">根拠: <a class="termdef" href="#def-Authoring-Tool" title="定義: オーサリングツール">オーサリングツール</a>が<a href="#def-Web-Content-Accessibility-Problem" title="定義: ウェブコンテンツの**アクセシビリティ問題**"  class="termdef">**アクセシビリティ問題** (WCAG)</a> を含む<span class="sc"><a class="termdef" href="#def-Web-Content" title="定義: ウェブコンテンツ">ウェブコンテンツ</a></span>を<span class="sc"><a href="#def-Content-Auto-Gen" title="定義: 自動生成されるコンテンツ" class="termdef">自動的に</a></span>生成する場合、<a href="#def-Author" title="定義: コンテンツ制作者" class="termdef">コンテンツ制作者</a>に追加の<a href="#def-Repairing" title="定義: 修正" class="termdef">修正</a>作業を強いることになる。</p>
1003:<p class="rationale">根拠: <a class="termdef" href="#def-Accessible-Web-Content" title="定義: アクセシブルなウェブコンテンツ">アクセシブルなウェブコンテンツ (WCAG)</a> の作成と保守に着手することをガイドすることによって、<a class="termdef" href="#def-Author" title="定義: コンテンツ制作者">コンテンツ制作者</a>の<a href="#def-Web-Content-Accessibility-Problem" title="定義: ウェブコンテンツの**アクセシビリティ問題**" class="termdef">ウェブコンテンツの**アクセシビリティ問題** (WCAG)</a> を軽減し、<a href="#def-Repairing" title="定義: 修正" class="termdef">修正</a>の負荷を少なくすることができる。</p>
1033:      <p class="rationale">根拠: 不適切に生成された<a href="#def-Alternative-Content" title="定義: 代替コンテンツ" class="termdef">代替コンテンツ</a>は、<a class="termdef" href="#def-Web-Content-Accessibility-Problem" title="定義: ウェブコンテンツの**アクセシビリティ問題**">ウェブコンテンツの**アクセシビリティ問題** (WCAG)</a> を生成し、アクセシビリティ<a href="#def-Checking" title="定義: チェック" class="termdef">チェック</a>を妨げる可能性がある。<br />
1167:    <h3 class="guideline"><a id="gl_b31" name="gl_b31"> </a> ガイドライン B.3.1: **アクセシビリティ問題**のためのチェック時にコンテンツ制作者を支援する。<span class="gl-only">[<a href="http://www.w3.org/TR/2015/NOTE-IMPLEMENTING-ATAG20-20150924/#gl_b31">B.3.1 の実装</a>]</span> </h3>
1168:    <p class="rationale">根拠: <a href="#def-Checking" title="定義: チェック" class="termdef">アクセシビリティのチェック</a>が<a class="termdef" href="#def-Authoring-Tool" title="定義: オーサリングツール">オーサリングツール</a>の統合された機能である場合、オーサリングプロセス中に<a href="#def-Web-Content-Accessibility-Problem" title="定義: ウェブコンテンツの**アクセシビリティ問題**" class="termdef">ウェブコンテンツの**アクセシビリティ問題**(WCAG)</a>を<a class="termdef" href="#def-Author" title="定義: コンテンツ制作者">コンテンツ制作者</a>に気付かせるのに役立ち、すぐに対処することができる。</p>
1175:    <li class="sc-note"><em class="note-handle">注記:</em> <a class="termdef" href="#def-Automated-Checking" title="定義: 自動チェック">自動</a>及び<a class="termdef" href="#def-Semi-Automated-Checking" title="定義: 半自動チェック">半自動チェック</a>は、多くの種類の<a href="#def-Web-Content-Accessibility-Problem" title="定義: ウェブコンテンツの**アクセシビリティ問題**" class="termdef">ウェブコンテンツの**アクセシビリティ問題** (WCAG)</a> が起こりうる (また促す)。しかし、この達成基準を満たすための最小要件は<a href="#def-Manual-Checking" title="定義: 手動チェック" class="termdef">手動チェック</a>である。手動チェックでは、オーサリングツールは<a class="termdef" href="#def-Author" title="定義: コンテンツ制作者">コンテンツ制作者</a>に問題を検出するための指示を与え、コンテンツ制作者自身が実行する。チェックの詳細については、<a href="http://www.w3.org/TR/2015/NOTE-IMPLEMENTING-ATAG20-20150924/#checking-types">Implementing ATAG 2.0 - Appendix B: Levels of Checking Automation</a>を参照</li></ul>
1187:  <p class="sc-title">潜在的なウェブコンテンツの**アクセシビリティ問題** (WCAG) が正しく認識されているかどうかを<a class="termdef" href="#def-Author" title="定義: コンテンツ制作者">コンテンツ制作者</a>の判断に頼る<a href="#def-Checking" title="定義: チェック" class="termdef">アクセシビリティのチェック</a>を<a class="termdef" href="#def-Authoring-Tool" title="定義: オーサリングツール">オーサリングツール</a>が提供している場合 (例えば、<a href="#def-Manual-Checking" title="定義: 手動チェック" class="termdef">手動チェック</a>や<a href="#def-Semi-Automated-Checking" title="定義: 半自動チェック" class="termdef">半自動チェック</a>など)、アクセシビリティチェックのプロセスは判断するための説明を提供する。<span class="level">(<strong>レベル A</strong>)</span></p>
1195:  <p class="sc-title">潜在的な<a href="#def-Web-Content-Accessibility-Problem" title="定義: ウェブコンテンツのアクセシビリティの問題" class="termdef">ウェブコンテンツの**アクセシビリティ問題**(WCAG)</a>が正しく認識されているかどうか、<a class="termdef" href="#def-Author" title="定義: コンテンツ制作者">コンテンツ制作者</a>の判断が必要な<a href="#def-Checking" title="定義: チェック" class="termdef">チェック</a>を<a class="termdef" href="#def-Authoring-Tool" title="定義: オーサリングツール">オーサリングツール</a>が提供している場合 (例えば、<a href="#def-Manual-Checking" title="定義: 手動チェック" class="termdef">手動チェック</a>や<a href="#def-Semi-Automated-Checking" title="定義: 半自動チェック" class="termdef">半自動チェック</a>)、関連コンテンツはコンテンツ制作者に特定される。<span class="level">(<strong>レベル A</strong>)</span></p>
1198:<li class="sc-note"><em class="note-handle">注記:</em> <a class="termdef" href="#def-Editing-View" title="定義: 編集ビュー">編集ビュー</a>の性質と潜在的なウェブコンテンツの**アクセシビリティ問題**(WCAG)の規模に応じて、特定には要素やレンダリングされた要素のハイライト、行番号の表示、または指示の提供が含まれる。</li></ul>
1227:<h3 class="guideline"><a id="gl_b32" name="gl_b32"> </a> ガイドライン B.3.2: **アクセシビリティ問題**を修正する際にコンテンツ制作者を支援する。 <span class="gl-only"> [<a href="http://www.w3.org/TR/2015/NOTE-IMPLEMENTING-ATAG20-20150924/#gl_b32">B.3.2 の実装</a>] </span> </h3>
1229:<p class="rationale">根拠: <a href="#def-Repairing" title="定義: 修正" class="termdef">修正</a>がオーサリングツールのプロセスに必要不可欠である場合、<a href="#def-Checking" title="定義: チェック" class="termdef">チェック</a>の有用性が大幅に向上し、<a href="#def-Web-Content-Accessibility-Problem" title="定義: ウェブコンテンツのアクセシビリティの問題" class="termdef">ウェブコンテンツの**アクセシビリティ問題** (WCAG)</a> が適切に対処される可能性がある。</p>
1235:    <li class="sc-note"><em class="note-handle">注記:</em> <a class="termdef" href="#def-Automated-Repairing" title="定義: 自動修正">自動修正</a>や<a class="termdef" href="#def-Automated-Checking" title="定義: 自動チェック">自動チェック</a>、<a class="termdef" href="#def-Semi-Automated-Repairing" title="定義: 半自動修正">半自動修正</a>では多くの<a href="#def-Web-Content-Accessibility-Problem" title="定義: ウェブコンテンツの**アクセシビリティ問題**" class="termdef">ウェブコンテンツの**アクセシビリティ問題** (WCAG)</a> が起こりうる (または促す)。ただし、この達成基準を満たすための最小要件は<a href="#def-Manual-Repairing" title="定義: 手動修正" class="termdef">手動修正</a>である。手動修正では、<a class="termdef" href="#def-Authoring-Tool" title="定義: オーサリングツール">オーサリングツール</a>は<a class="termdef" href="#def-Author" title="定義: コンテンツ制作者">コンテンツ制作者</a>に問題を修正するための指示を提供し、コンテンツ制作者自身が実行する。修正の詳細については <a href="http://www.w3.org/TR/2015/NOTE-IMPLEMENTING-ATAG20-20150924/#repair-types">Implementing ATAG 2.0 - Appendix C: Levels of Repair Automation</a> を参照。</li></ul>
1277:  <p class="sc-title"> <a class="termdef" href="#def-Authoring-Tool" title="definition: authoring tool">オーサリングツール</a>には、<a title="definition: accessible content support features" class="termdef" href="#def-Accessible-Content-Support-Features">アクセシブルなコンテンツのサポート機能</a>をオフにする<span class="sc-bullet"><a href="#def-Option" title="definition: option" class="termdef">オプション</a></span>が含まれていない、又は、これらの機能をオフにできる場合、<a href="#def-Author" title="definition: authors" class="termdef">コンテンツ制作者</a>は、<a title="definition: web content accessibility problem" class="termdef" href="#def-Web-Content-Accessibility-Problem">コンテンツの**アクセシビリティ問題** (WCAG)</a> のリスクが増大すること知らされる。<span class="level">(<strong>レベル AA</strong>)</span></p>

# 「アクセシビリティの問題」
273:                <li><a href="#gl_b31">B.3.1. アクセシビリティの問題のためのチェック時にコンテンツ制作者を支援する</a></li>
275:                <li><a href="#gl_b32">B.3.2. アクセシビリティの問題を修正する際にコンテンツ制作者を支援する</a></li>
332:  <p>この2つの利用者のニーズを満たすための要件は、ガイドライン内で分かりやすくするために分離されているが、利用者作成コンテンツの流行において、実際には相互に深く関連していることに注意すべきである。例えば、利用者がオンラインフォーラムに参加する場合、利用者はしばしばコンテンツを作成し、他の利用者によって作成されたコンテンツと組み合わされる。オーサリングユーザインタフェース、または他のフォーラム利用者によって作成されたコンテンツのアクセシビリティの問題は、フォーラムの全体的なアクセシビリティを低下させる。</p>
395:      <li><a name="part_a_applic_note_2" id="part_a_applic_note_2"></a><strong class="handle">反映されたコンテンツのアクセシビリティの問題:</strong> <a class="termdef" href="#def-Authoring-Tool" title="定義: オーサリングツール">オーサリングツール</a>は<a href="#def-Editing-View" title="定義: 編集ビュー" class="termdef">編集ビュー</a>に表示されている<a class="termdef" href="#def-Content-Being-Edited" title="定義: 編集中のウェブコンテンツ">編集中のウェブコンテンツ</a>が障害を持つ<a class="termdef" href="#def-Author" title="定義: コンテンツ制作者">コンテンツ制作者</a>にとってよりアクセシブルな方法で提供されていることを保証する責任がある (例: コンテンツの<span class="sc-bullet"><a class="termdef" href="#def-Text-Alternatives" title="非テキストコンテンツの代替テキスト">代替テキスト</a></span>が<a class="termdef" href="#def-Programmatically-Determined" title="定義: プログラムによる解釈可能">プログラムによる解釈可能</a>であることを保証する)。しかし、<a href="#def-Authoring-Interface-Accessibility-Problem" title="定義: オーサリングツールのユーザインタフェースの**アクセシビリティの問題**" class="termdef">オーサリングツールのユーザインタフェースの**アクセシビリティの問題**</a>が編集されているコンテンツによって発生している箇所 (例: コンテンツ内の画像にテキストによる代替が不足している場合) では、<a href="#def-Authoring-Tool-Interface" title="定義: オーサリングツールのユーザインタフェース" class="termdef">オーサリングツールのユーザインタフェース</a>のアクセシビリティが不足しているとは見なされない。<br/>
1195:  <p class="sc-title">潜在的な<a href="#def-Web-Content-Accessibility-Problem" title="定義: ウェブコンテンツのアクセシビリティの問題" class="termdef">ウェブコンテンツの**アクセシビリティの問題**(WCAG)</a>が正しく認識されているかどうか、<a class="termdef" href="#def-Author" title="定義: コンテンツ制作者">コンテンツ制作者</a>の判断が必要な<a href="#def-Checking" title="定義: チェック" class="termdef">チェック</a>を<a class="termdef" href="#def-Authoring-Tool" title="定義: オーサリングツール">オーサリングツール</a>が提供している場合 (例えば、<a href="#def-Manual-Checking" title="定義: 手動チェック" class="termdef">手動チェック</a>や<a href="#def-Semi-Automated-Checking" title="定義: 半自動チェック" class="termdef">半自動チェック</a>)、関連コンテンツはコンテンツ制作者に特定される。<span class="level">(<strong>レベル A</strong>)</span></p>
1229:<p class="rationale">根拠: <a href="#def-Repairing" title="定義: 修正" class="termdef">修正</a>がオーサリングツールのプロセスに必要不可欠である場合、<a href="#def-Checking" title="定義: チェック" class="termdef">チェック</a>の有用性が大幅に向上し、<a href="#def-Web-Content-Accessibility-Problem" title="定義: ウェブコンテンツのアクセシビリティの問題" class="termdef">ウェブコンテンツの**アクセシビリティの問題** (WCAG)</a> が適切に対処される可能性がある。</p>
1473:    <dt><dfn><a id="def-Accessibility-Problem" name="def-Accessibility-Problem"></a>アクセシビリティの問題 (accessibility problems)</dfn></dt>
1474:    <dd>ATAG 2.0 では、2種類のアクセシビリティの問題を認識している:
1476:	    <li><dfn><a id="def-Authoring-Interface-Accessibility-Problem" name="def-Authoring-Interface-Accessibility-Problem"></a>オーサリングツールのアクセシビリティの問題:</dfn>
1479:	<li><a id="def-Web-Content-Accessibility-Problem" name="def-Web-Content-Accessibility-Problem"></a><dfn>ウェブコンテンツのアクセシビリティの問題 (WCAG):</dfn>
1594:    <dd><a class="termdef" href="#def-Web-Content-Accessibility-Problem" title="定義: ウェブコンテンツのアクセシビリティの問題">ウェブコンテンツのアクセシビリティの問題 (WCAG)</a> を評価するプロセス。ATAG 2.0 では、テスト自動化のレベルに基づいて、3種類のチェック方法を認識している:
1781:    <dd><a class="termdef" href="#def-Web-Content" title="definition: web content">ウェブコンテンツ</a>内で識別された<a class="termdef" href="#def-Web-Content-Accessibility-Problem" title="definition: web content accessibility problem">ウェブコンテンツのアクセシビリティの問題</a>が解決されるプロセス。ATAG 2.0は、自動化のレベルの増加に基づいて、3種類の修正を認識する。

**Comment by momdo** [comment]
例えば、

アクセシビリティ**についての**問題 (accessibility problems)

とするのもありかな、と思いました。

**Comment by bakera** [comment]
もんどさん案に一票で。

**Comment by motchie** [comment]
1. 用語集の次の箇所

**Comment by motchie** [comment]
「アクセシビリティ問題」も「アクセシビリティの問題」も、まだ存在するなぁ。

**Comment by motchie** [comment]
# 「アクセシビリティの問題」
273行目:
```
                <li><a href="#gl_b31">B.3.1. アクセシビリティの問題のためのチェック時にコンテンツ制作者を支援する</a></li>
```
275行目:
```
                <li><a href="#gl_b32">B.3.2. アクセシビリティの問題を修正する際にコンテンツ制作者を支援する</a></li>
```
332行目:
```
  <p>この二つの利用者...作成されたコンテンツのアクセシビリティの問題は、フォーラムの全体的なアクセシビリティを低下させる。</p>
```
395行目:
```
      <li><a name="part_a_applic_note_2" id="part_a_applic_note_2"></a><strong class="handle">反映されたコンテンツのアクセシビリティの問題:</strong>
```
1475行目:
```
    <dd>ATAG 2.0 では、2種類のアクセシビリティの問題を認識している:
```

**Comment by motchie** [comment]
目次と、参照先の見出しの表記揺れもあるぞ...
273行目:
```
<li><a href="#gl_b31">B.3.1. アクセシビリティの問題のためのチェック時にコンテンツ制作者を支援する</a></li>
```
1168行目:
```
    <h3 class="guideline"><a id="gl_b31" name="gl_b31"> </a> ガイドライン B.3.1: アクセシビリティ問題のためのチェック時にコンテンツ制作者を支援する。
```

**Comment by motchie** [comment]
@momdo @bakera 用語集を修正後にも
1.「アクセシビリティ問題」「アクセシビリティの問題」の表記揺れが存在します。
2. 目次と参照先の見出しの表記揺れもあります。

1. については、それぞれ原文を洗い出して翻訳の揺れを吸収する感じですか?
2. についても、1と同様に、どちらかを基準と定めて表記揺れを治したいです。

よろしくお願いいたします。

**Comment by motchie** [comment]
#110 も、こちらでまとめて扱った方がよさそう。

**Comment by momdo** [comment]
#110 については別途PRいただいて解決しましたので一応。

**Comment by caztcha** [comment]
PR #143 にて対応中です。

**Comment by momdo** [comment]
マージしたのでCloseします。
