### ISSUE TITLE
「関連づけ」 vs 「関連付け」

### ISSUE THREAD

**Issue by motchie** [waic/atag20-ja#78]
#40 より。
まずは該当箇所の列挙から。

**Comment by motchie** [comment]
# 関連づけ

467:	  <p class="sc-title"><a class="termdef" href="#def-Editing-View" title="定義: 編集ビュー">編集ビュー</a>が<a class="termdef" href="#def-Non-Text-Objects" title="定義: 非テキストコンテンツ">非テキストコンテンツ</a>を<a class="termdef" href="#def-Content-Renderings" title="定義: コンテンツレンダリング">レンダリング</a>する場合、<a href="#def-Associated-Alternative-Content" title="定義: 代替コンテンツ" class="termdef">プログラムによって**関連づけ**られた</a><a class="termdef" href="#def-Text-Alternatives" title="非テキストコンテンツの代替テキスト">非テキストコンテンツの代替テキスト</a>は<a class="termdef" href="#def-Programmatically-Determined" title="定義: プログラムによる解釈">プログラムによる解釈</a>することができる。<span class="level">（<strong>レベル A</strong>）</span></p>

# 関連付け

583:<p class="sc-title"><a class="termdef" href="#def-Authoring-Tool" title="definition: authoring tool">オーサリングツール</a>がキーボードコマンドを提供している場合、</p>オーサリングツールは<a class="termdef" href="#def-Author" title="definition: authors">コンテンツ制作者</a>が<a href="#def-Authoring-Tool-Interface" title="definition: authoring tool user interface" class="termdef">オーサリングツールのユーザインタフェース</a> <a class="termdef" href="#def-UI-Component" title="definition: user interface component">コンポーネント</a>と**関連付け**られたキーボードコマンドを確認する方法を提供する。<span class="level">（<strong>レベル AAA</strong>）</span>
675:      <h4 class="sc-title"><a id="sc_a342" name="sc_a342"> </a>A.3.4.2 プログラミングによる**関連付け**からのナビゲート: </h4><p class="sc-title"><a class="termdef" href="#def-Editing-View" title="definition: editing view">編集ビュー</a>が<a class="termdef" href="#def-Web-Content" title="definition: web content">ウェブコンテンツ</a>内のプログラミングによる<a href="#def-Relationships" title="definition: relationships" class="termdef">**関連付け**</a>の編集を可能にする場合、関連しているコンテンツ間のナビゲーションをサポートするメカニズムが提供されている。<span class="level">（<strong>レベル AAA</strong>）</span></p>
677:        <li class="sc-note"><em class="note-handle">注記:</em> <span class="sc-title"><a href="#def-Web-Content-Technology" title="definition: technology (Web content)" class="termdef">ウェブコンテンツ技術</a>および<a class="termdef" href="#def-Authoring-Tool" title="definition: authoring tool">オーサリングツール</a>の性質によって、関連性は、これらに限定するものではないが、要素のネスティング、見出し、ラベリング、プログラミングによる意味付け、及びIDの**関連付け**が含まれる。</span></li>
1039:        <p class="sc-title"><a class="termdef" href="#def-Authoring-Tool" title="定義: オーサリングツール">オーサリングツール</a>が非テキストコンテンツを追加するための機能を提供する場合、<a href="#def-Associated-Alternative-Content" title="定義: 代替コンテンツ" class="termdef">プログラムで**関連付け**られた</a><a class="termdef" href="#def-Text-Alternatives" title="非テキストコンテンツのテキストによる代替">非テキストコンテンツのテキストによる代替</a>を<a href="#def-Author" title="定義: コンテンツ制作者" class="termdef">コンテンツ制作者</a>が編集することができる。<span class="level">(<strong>レベル A</strong> は WCAG 2.0 のレベル A の達成基準; <strong>レベル AA</strong> は WCAG 2.0 のレベル A と AA の達成基準; <strong>レベル AAA</strong> は WCAG 2.0 のすべての達成基準を満たす)</span></p>
1069:  <p class="sc-title"><a class="termdef" href="#def-Authoring-Tool" title="定義: オーサリングツール">オーサリングツール</a>が非テキストコンテンツを追加するための機能を提供する場合、<a href="#def-Author" title="定義: コンテンツ制作者" class="termdef">コンテンツ制作者</a>が<a href="#def-Associated-Alternative-Content" title="定義: 代替コンテンツ" class="termdef">プログラムで**関連付け**られた</a><a class="termdef" href="#def-Text-Alternatives" title="非テキストコンテンツのテキストによる代替">非テキストコンテンツのテキストによる代替</a>を入力する時、次のすべてを満たす。<span class="level">(<strong>レベル AAA</strong>)</span></p>
1218:  <h4 class="sc-title"><a id="sc_b315" name="sc_b315"> </a>B.3.1.5 結果のプログラムによる**関連付け**: </h4>
1219:  <p class="sc-title"><a class="termdef" href="#def-Authoring-Tool" title="definition: authoring tool">オーサリングツール</a>が<a href="#def-Checking" title="definition: checking" class="termdef">チェック</a>を提供する場合、<a class="termdef" href="#def-Authoring-Tool" title="definition: authoring tool">オーサリングツール</a>は、アクセシビリティの<a href="#def-Checking" title="definition: checking" class="termdef">チェック</a>結果を、チェックされた<a class="termdef" href="#def-Web-Content" title="definition: web content">ウェブコンテンツ</a>とプログラムで**関連付け**ることができる。<span class="level">(<strong>レベル AA</strong>)</span></p>
1484:    <dd><a href="#conf-rel-wcag">WCAG 2.0</a> の達成基準 (レベルA、AA、AAA) を満たすために<a href="#def-Web-Content" title="定義: ウェブコンテンツ" class="termdef">ウェブコンテンツ</a>が必ず含まなければならない情報。例えば、<a href="#def-Associated-Alternative-Content" title="定義: プログラムで**関連付け**られる代替コンテンツ" class="termdef">プログラムで**関連付け**られる代替コンテンツ</a> (画像に対するテキストによる代替、など)、ウィジェットに対する<a href="#def-Role" title="定義: 役割 (Role)" class="termdef">役割 (Role)</a> やステートの情報、複雑なテーブル内部の<a href="#def-Relationships" title="定義: 関係性" class="termdef">関係性</a>。<br />
1494:        <li><dfn><a id="def-Text-Alternatives" name="def-Text-Alternatives"></a>非テキストコンテンツに対するテキストによる代替:</dfn> 非テキストコンテンツに<a href="#def-Associated-Alternative-Content" title="定義: プログラムで**関連付け**られる" class="termdef">プログラムで**関連付け**られる</a>テキスト、又は非テキストコンテンツにプログラムで**関連付け**られるテキストから参照されるテキスト。例えば、ある図表の画像には、テキストによる代替が2つある: 図表の後の段落に記述される説明と、図表に対する短いテキストによる代替でその後に説明が続く旨を示すもの、である。</li>
1501:      <a id="def-Associated-Alternative-Content" name="def-Associated-Alternative-Content"></a><dfn>プログラムで**関連付け**られる代替コンテンツ: </dfn>代替コンテンツの場所や目的が、代替対象の元コンテンツから、<a class="termdef" href="#def-Programmatically-Determined" title="定義: プログラムによる解釈">プログラムによる解釈</a>が可能なもの。例えば段落は、画像に対するテキストによる代替として提供されることがあるが、それはこの関係性が適切にエンコードされている場合 (例えば、「aria-labelledby」によって) にのみ、プログラムで**関連付け**られていると言える。<br />
1502:<em>注記:</em> ATAG 2.0 において代替コンテンツとは通常、プログラムで**関連付け**られる代替コンテンツを指す。</li>
1778:    <dd>異なる<a href="#def-Web-Content" title="definition: web content" class="termdef">コンテンツ</a>間の意味のある**関連付け**。</dd>

**Comment by momdo** [comment]
「関連付け」のほうがたくさんあるので、「関連付け」でよいのではないでしょうか？（雑）

**Comment by momdo** [comment]
WCAG 2.0でも「関連付け」となっている。

**Comment by bakera** [comment]
「関連付け」にしましょう。
