### ISSUE TITLE
「サポートする」 vs 「支援する」

### ISSUE THREAD

**Issue by motchie** [waic/atag20-ja#81]
#40 より。
まずは該当箇所の列挙から。

**Comment by motchie** [comment]
# サポートする

251:        <li><a href="#part_b">B. アクセシブルなコンテンツの制作を**サポートする**</a>
280:                <li><a href="#gl_b41">B.4.1. アクセシブルなコンテンツの制作を**サポートする**機能が利用可能であることを確保する</a></li>
368: <p>ATAG 2.0 を実装する際、<a class="termdef" href="#def-Developer" title="definition: authoring tool developers">オーサリングツールの開発者</a>は、よりアクセシブルなオーサリングを**サポートする**機能を、<a class="termdef" href="#def-Authoring-Tool" title="definition: authoring tool">オーサリングツール</a>の他の機能と同じ &quot;ルック・アンド・フィール&quot; になるように注意して統一すべきである。厳密に統一することで次のような可能性が生まれる:</p>
675:      <h4 class="sc-title"><a id="sc_a342" name="sc_a342"> </a>A.3.4.2 プログラミングによる関連付けからのナビゲート: </h4><p class="sc-title"><a class="termdef" href="#def-Editing-View" title="definition: editing view">編集ビュー</a>が<a class="termdef" href="#def-Web-Content" title="definition: web content">ウェブコンテンツ</a>内のプログラミングによる<a href="#def-Relationships" title="definition: relationships" class="termdef">関連付け</a>の編集を可能にする場合、関連しているコンテンツ間のナビゲーションを**サポートする**メカニズムが提供されている。<span class="level">（<strong>レベル AAA</strong>）</span></p>
866:<h2><a id="part_b" name="part_b"> </a>パート B: アクセシブルなコンテンツの制作を**サポートする**</h2>
987:      <p class="rationale"><strong><a name="gl_b11-rationale" id="gl_b11-rationale"> </a></strong>根拠: <a class="termdef" href="#def-Accessible-Web-Content" title="定義: アクセシブルなウェブコンテンツ">アクセシブルなウェブコンテンツ (WCAG)</a> の制作を**サポートする**には、少なくとも、<a class="termdef" href="#def-Authoring-Tool" title="定義: オーサリングツール">オーサリングツール</a>を用いて <a href="#conf-rel-wcag">WCAG 2.0</a> に適合した<a class="termdef" href="#def-Web-Content" title="定義: ウェブコンテンツ">ウェブコンテンツ</a>を制作することが可能なことである。</p>
1246:<h3 class="guideline"><a id="gl_b41" name="gl_b41"> </a> ガイドライン B.4.1: アクセシブルなコンテンツの制作を**サポートする**機能が利用可能であることを確保する。
1488:    <dd><a class="termdef" href="#def-Content-Being-Edited" title="定義: 編集中のウェブコンテンツ">編集中のウェブコンテンツ</a>のアクセシビリティを高めるために<a href="#def-Author" title="定義: コンテンツ制作者" class="termdef">コンテンツ制作者</a>を直接**サポートする**<a class="termdef" href="#def-Authoring-Tool" title="定義: オーサリングツール">オーサリングツール</a>の機能。これらは、ATAG 2.0 の<a href="#part_b">パートB</a>の達成基準を満たすためになくてはならない機能である。</dd>
1611:        <li><dfn><a id="def-Content-Being-Edited" name="def-Content-Being-Edited">編集中のコンテンツ (content being edited):</a></dfn> <a class="termdef" href="#def-Author" title="定義: コンテンツ制作者">コンテンツ制作者</a>が、<a href="#def-Authoring-Session" title="定義: オーサリングセッション" class="termdef">オーサリングセッション</a>中に改変できるウェブコンテンツ。編集中のコンテンツは、ひとつの完結したコンテンツ (例えば、画像、スタイルシート) であることもあれば、より大きなコンテンツ (例えば、ステータス更新) の一部のみであることもある。編集中のコンテンツには、<a href="#def-Authoring-Tool" title="定義: オーサリングツール" class="termdef">オーサリングツール</a>が**サポートする**<a href="#def-Web-Content-Technology" title="定義: 技術 (ウェブコンテンツ)" class="termdef">ウェブコンテンツ技術</a>のコンテンツのみが含まれる (例えば、WYSIWYG の HTML エディタではウェブページの HTML コンテンツを編集できるが、画像は編集できない)。</li>
1843:    <dd><a href="#def-Author" title="definition: authors" class="termdef">コンテンツ制作者</a>が<a class="termdef" href="#def-Content-Being-Edited" title="definition: web content being edited">編集中のウェブコンテンツ</a>と対話するために使用するユーザインタフェース機能。 ATAG 2.0は、それらが編集を**サポートする**かどうかに応じてビューを分類する:

# 支援する

234:                <li><a href="#gl_a33">A.3.3.  ( オーサリングツールのユーザインタフェースに対して ) コンテンツ制作者が発作を引き起こすような閃光を防ぐように**支援する**</a></li>
265:                <li><a href="#gl_b23">B.2.3. コンテンツ制作者が非テキストコンテンツの代替コンテンツを管理するのを**支援する**</a></li>
267:                <li><a href="#gl_b24">B.2.4. アクセシブルなテンプレートでコンテンツ制作者を**支援する**</a></li>
268:                <li><a href="#gl_b25">B.2.5. 事前に作成されたアクセシブルなコンテンツでコンテンツ制作者を**支援する**</a></li>
273:                <li><a href="#gl_b31">B.3.1. アクセシビリティの問題のためのチェック時にコンテンツ制作者を**支援する**</a></li>
275:                <li><a href="#gl_b32">B.3.2. アクセシビリティの問題を修正する際にコンテンツ制作者を**支援する**</a></li>
643:	<h3 class="guideline"><a name="gl_a33" id="gl_a33"> </a>ガイドライン A.3.3: （オーサリングツールのユーザインタフェースに対して）コンテンツ制作者が発作を引き起こすような閃光を防ぐように**支援する**。 <span class="gl-only"> [<a href="http://www.w3.org/TR/2015/NOTE-IMPLEMENTING-ATAG20-20150924/#gl_a33">A.3.3 を実装する</a>] </span>
1029:<h3 class="guideline"><a id="gl_b23" name="gl_b23"> </a> ガイドライン B.2.3: コンテンツ制作者が非テキストコンテンツの代替コンテンツを管理するのを**支援する**。
1081:    <h3 class="guideline"><a id="gl_b24" name="gl_b24"> </a> ガイドライン B.2.4: アクセシブルなテンプレートでコンテンツ制作者を**支援する**。
1139:  <h3 class="guideline"><a id="gl_b25" name="gl_b25"> </a> ガイドライン B.2.5: 事前に作成されたアクセシブルなコンテンツでコンテンツ制作者を**支援する**。 <span class="gl-only">[<a href="http://www.w3.org/TR/2015/NOTE-IMPLEMENTING-ATAG20-20150924/#gl_b25">B.2.5 の実装</a>]</span> </h3>
1167:    <h3 class="guideline"><a id="gl_b31" name="gl_b31"> </a> ガイドライン B.3.1: アクセシビリティ問題のためのチェック時にコンテンツ制作者を**支援する**。<span class="gl-only">[<a href="http://www.w3.org/TR/2015/NOTE-IMPLEMENTING-ATAG20-20150924/#gl_b31">B.3.1 の実装</a>]</span> </h3>
1227:<h3 class="guideline"><a id="gl_b32" name="gl_b32"> </a> ガイドライン B.3.2: アクセシビリティ問題を修正する際にコンテンツ制作者を**支援する**。 <span class="gl-only"> [<a href="http://www.w3.org/TR/2015/NOTE-IMPLEMENTING-ATAG20-20150924/#gl_b32">B.3.2 の実装</a>] </span> </h3>
1251:      <p class="rationale">根拠: <a class="termdef" href="#def-Accessible-Content-Support-Features" title="定義: アクセシブルなコンテンツを**支援する**機能">アクセシブルなコンテンツを**支援する**機能</a>は、機能をオンにして<a href="#def-Authoring-Tool-Interface" title="定義: オーサリングツールのユーザインタフェース" class="termdef">オーサリングツールのユーザインタフェース</a>で合理的な<a class="termdef" href="#def-Prominence" title="定義: 顕在性">顕在性</a>が与えられることで、使用される可能性が高くなる。</p>
1255:        <h4 class="sc-title"><a id="sc_b411" name="sc_b411"> </a>B.4.1.1 デフォルトで有効な機能: </h4><p class="sc-title"> すべての<a title="定義: アクセシブルなコンテンツを**支援する**機能" class="termdef" href="#def-Accessible-Content-Support-Features">アクセシブルなコンテンツを**支援する**機能</a>はデフォルトでオンになっている。<span class="level">(<strong>レベル A</strong>)</span></p>
1265:        <p class="sc-title"><a class="termdef" href="#def-Authoring-Tool" title="定義: オーサリングツール">オーサリングツール</a>には、<a title="定義: アクセシブルなコンテンツを**支援する**機能" class="termdef" href="#def-Accessible-Content-Support-Features">アクセシブルなコンテンツを**支援する**機能</a>をオフにする<span class="sc-bullet"><a href="#def-Option" title="定義: 選択肢" class="termdef">選択肢</a></span>が含まれていない、またはオフになっている機能をオンに戻すことができる。<span class="level">(<strong>レベル A</strong>)</span></p>
1299:      <p class="rationale">根拠: 一部の<a class="termdef" href="#def-Author" title="定義: コンテンツ制作者">コンテンツ制作者</a>は、<a class="termdef" href="#def-Accessible-Content-Support-Features" title="定義: アクセシブルなコンテンツを**支援する**機能">アクセシブルなコンテンツを**支援する**機能</a> (例えば、<span class="sc-bullet"><a class="termdef" href="#def-Text-Alternatives" title="非テキストコンテンツのテキストによる代替">テキストによる代替</a></span>に対する<a href="#def-Prompt" title="定義: 要求" class="termdef">要求</a>への対応方法、アクセシビリティ<a href="#def-Checking" title="定義: チェック" class="termdef">チェック</a>ツールの使用方法など) を使う上でサポートが必要である。アクセシブルなオーサリングを習慣的な慣例として提示するか、あるいは少なくともアクセシブルではない慣例を提示しないことは、コンテンツ制作者に対してアクセシビリティの受け入れを促進するのに役立つ。</p>
1316:        <p class="sc-title">すべての<a class="termdef" href="#def-Accessible-Content-Support-Features" title="定義: アクセシブルなコンテンツを**支援する**機能">アクセシブルなコンテンツを**支援する**機能</a>の使用方法は<a class="termdef" href="#def-Documentation" title="定義: ドキュメンテーション">ドキュメンテーション</a>に記載されている。<span class="level">(<strong>レベル A</strong>)</span></p>
1440:  <p>上記の適合表明の必須項目に加えて、コンテンツ制作者を**支援する**ために追加情報を提供することを検討する。追加する情報として推奨するものを以下に挙げる:</p>
1668:    <dd><a href="#def-Authoring-Tool" title="定義: オーサリングツール" class="termdef">オーサリングツール</a>の使用を**支援する**ための情報。この情報は、電子的又は他の方法で提供されてもよい。また、この情報にはヘルプ、マニュアル、インストール手順、サンプル<a class="termdef" href="#def-Workflow" title="定義: ワークフロー">ワークフロー</a>、<a href="#def-Tutorial" title="定義: チュートリアル" class="termdef">チュートリアル</a>などが含まれる。</dd>

**Comment by momdo** [comment]
ぱっと見でWCAG 2.0は「サポートする」「支援する」が混在しているようです。

**Comment by bakera** [comment]
ATを「支援技術」としていて、この場合は支援 = assist です。
assistは支援、supportはサポートという訳し分けで成立すると良いのですが。

**Comment by motchie** [comment]
master ブランチの日本語訳でgrepした結果:
- `grep サポートする docs/index.html|wc -l` → 10
- `grep 支援する docs/index.html|wc -l` → 19

**Comment by motchie** [comment]
原文を "assist" で grep して "assistive" を除外した結果 → 3件
```
327:    2.0. This document includes recommendations for assisting <a class="termdef" href="#def-Developer" title="definition: authoring tool developers">authoring tool developers</a> to make their <a class="termdef" href="#def-Authoring-Tool" title="definition: authoring tool">authoring tools</a> more accessible to people with disabilities, including auditory, cognitive, neurological, physical, speech, and visual disabilities. </p>
1478:  <p>In addition to the required components of a conformance claim above, consider providing additional information to assist authors. Recommended additional information includes:</p>
1551:          <li>screen magnifiers, and other visual reading assistants, which are used by people with visual, perceptual, and physical print disabilities to change text font, size, spacing, color, synchronization with speech, etc. in order improve the visual readability of rendered text and images;</li>```

**Comment by motchie** [comment]
上記、残り3件で対応する日本語訳の現状:

# (原文の) 327行目: 
327: 2.0. This document includes recommendations for assisting authoring tool developers to make their authoring tools more accessible to people with disabilities, including auditory, cognitive, neurological, physical, speech, and visual disabilities.

## 現状の対応する日本語訳:
この文書にはオーサリングツールの開発者が、聴覚、認知、神経、身体、発話、および視覚障害を含む、障害を持つ人々にとってオーサリングツールをよりアクセシブルにするための推奨事項が記載されている。

→ "assisting" は 「にするための」になっているので、本 issue の対象外と判断

# (原文の) 1478行目:
In addition to the required components of a conformance claim above, consider providing additional information to assist authors. Recommended additional information includes:

## 現状の対応する日本語訳:
上記の適合表明の必須項目に加えて、コンテンツ制作者を支援するために追加情報を提供することを検討する。

→ "assist" が 「支援」になっているので、修正の必要なし。

# (原文の) 1551行目:
screen magnifiers, and other visual reading assistants, which are used by people with visual, perceptual, and physical print disabilities to change text font, size, spacing, color, synchronization with speech, etc. in order improve the visual readability of rendered text and images;

## 現状の対応する日本語訳:
画面拡大及びその他の視覚的な表示に関する支援技術。視覚障害、知覚障害、及び読書困難などの障害のある人が、レンダリング後のテキスト及び画像の視覚的な読みやすさを改善するために、テキストのフォント、サイズ、間隔、色、音声との同期などを変更するのに使用している。

→ "visual reading assistants" が 「視覚的な表示に関する支援技術」なのはいいのか...。ただ 「"assist" は支援」というルールには則っている。

**Comment by motchie** [comment]
あれ、表記揺れは "support" に集中しているのか...?

**Comment by motchie** [comment]
原文を "support" で grep した結果 → 45行。
あれ、[「支援する」と「サポートする」の合計](https://github.com/waic/atag20-ja/issues/81#issuecomment-524528219)より多いぞ...

**Comment by momdo** [comment]
@motchie 
パッと目に入ったので https://github.com/waic/atag20-ja/issues/81#issuecomment-524529455 についてコメントしておくと、

> → "assisting" は 「にするための」になっているので、本 issue の対象外と判断

そうではなくて、for assisting authoring tool developersがまるごと日本語訳から抜けているだけです。

**Comment by motchie** [comment]
@momdo 
> そうではなくて、for assisting authoring tool developersがまるごと日本語訳から抜けているだけです。

ぐはあ...。ありがとうございます。

**Comment by motchie** [comment]
@momdo ん、ごめんなさい
> This document includes recommendations for assisting authoring tool developers 

は
「オーサリングツールの開発者が、... ための推奨事項」ではない、ということでしょうか?

**Comment by momdo** [comment]
@motchie 
まあ、まるっと抜けているというわけでもないですが（よく見れば「オーサリングツールの開発者が」とはある）どっちにせよassistの意味を単に「する」とするのは微妙では。

**Comment by motchie** [comment]
@momdo 翻訳の修正は必要ということですね。この issue で対応します！

**Comment by motchie** [comment]
> この文書には<a class="termdef" href="#def-Developer" title="定義: オーサリングツールの開発者">オーサリングツールの開発者</a>が、聴覚、認知、神経、身体、発話、および視覚障害を含む、障害を持つ人々にとって<a class="termdef" href="#def-Authoring-Tool" title="定義: オーサリングツール">オーサリングツール</a>をよりアクセシブルにすることを支援するための推奨事項が記載されている。

こんな感じ...?

**Comment by motchie** [comment]
> 原文を "support" で grep した結果 → 45行。
> あれ、[「支援する」と「サポートする」の合計](https://github.com/waic/atag20-ja/issues/81#issuecomment-524528219)より多いぞ...

原文のassistやsupportから該当箇所を洗い出すアプローチより、日本語訳の「支援する」「サポートする」からアプローチした方がいいかもしれないな...

**Comment by motchie** [comment]
# 日本語の「サポート」「支援」の洗いだしと原文との比較(WIP)
## サポート
| 日本語行番号 | 日本語 | 原文 | 判定 |
| --- | --- | --- | --- |
| 170 | 可能にし、サポートし、促進するための | designed to enable, support, and promote | ● |
| 251 | コンテンツの制作をサポートする | Support the production of  | ? |
| 271 | サポートされる | Authors are supported | ● |
| 280 | 制作をサポートする機能 | features that support the production | ● |
| 329 | サポートされ、ガイドされる | authors are enabled, supported, | ● |
| 353 | オーサリングツールによるサポート | relates to support by authoring tools | ● |
| 368 | オーサリングをサポートする機能 | features that support more accessible | ● |
| 675 | ナビゲーションをサポートするメカニズム | provided that support navigation | ● |
| 867 | コンテンツの制作をサポートする | Support the production of accessible content | ? |
| 880 | アクセシブルなコンテンツのサポート機能 | Accessible content support features | ● |
| 947 | コピー＆ペーストをサポートしている | authoring tool supports copy and paste | ● |
| 982 | コンテンツ生成をサポートされる | Authors are supported | ? |
| 988 | ウェブコンテンツ (WCAG)の制作をサポートするには | Rationale: To support accessible web content | ? |
| 1166 | コンテンツのアクセシビリティ改善をサポート | Authors are supported in | ? |
| 1247 | 制作をサポートする機能 | features that support the production | ? |
| 1278 | 定義: アクセシブルなコンテンツのサポート機能 | accessible content support features | ? |
| 1278 | アクセシブルなコンテンツのサポート機能 | accessible content support features | ? |

**Comment by momdo** [comment]
@motchie 
上記表の判定の列にある記号（●と？）がどういう意味なのか、明らかにしておいてもらえると助かります。

**Comment by motchie** [comment]
> 上記表の判定の列にある記号（●と？）がどういう意味なのか、明らかにしておいてもらえると助かります。

@momdo 
コメントありがとうございます。
今、[assistは支援、supportはサポートという訳し分けで成立する](https://github.com/waic/atag20-ja/issues/81#issuecomment-477926114) かの確認を進めています。
● は、support = サポート という訳で問題なさそうと判断したもの。？ は、現状の訳で サポートと訳されているものの、「支援」に修正した方がよいのでは？と考えているもの、です。

**Comment by momdo** [comment]
@motchie

ありがとうございます。
追加の質問になるのですが、
> ● は、support = サポート という訳で問題なさそうと判断したもの。？ は、現状の訳で サポートと訳されているものの、「支援」に修正した方がよいのでは？と考えているもの、です。

これは、supportを「支援」と訳すのが適当だと思う箇所があると考えている、という理解であっているでしょうか？

**Comment by motchie** [comment]
@momdo 

> これは、supportを「支援」と訳すのが適当だと思う箇所があると考えている、という理解であっているでしょうか？

ありがとうございます。
確信まではいきませんが、少なくとも「サポート」のままでは訳として適切ではなく、
よりよい訳の候補として「支援」がよいのではないか、と考えている箇所が「？」の行です。

**Comment by momdo** [comment]
@motchie

例えばpromptのように品詞によって訳を変えるとか、イディオムになったときに変えるとかならわかりやすいですが、そのような規則性は、見つけられそうですか？（ちょっと表からはわかりませんでした）

**Comment by motchie** [comment]
@momdo<https://github.com/momdo>

まだ作業中なので、ちょっと待ってやっておくんなさい...。

**Comment by caztcha** [comment]
## 「支援する」「支援される」の洗い出し

| 行番号 | 日本語の訳出 | 原文の記載 (および対応案) |
| ---- | ---- | ---- |
| 1580 | 支援される | aided (ママでOK) |
| 1768 | 支援される | aided (ママでOK) |
| 234 | A.3.3.  (オーサリングツールのユーザインタフェース向け) コンテンツ制作者が発作を引き起こすような閃光を防ぐように支援する | help (ママでOK) |
| 265 | B.2.3. コンテンツ制作者が非テキストコンテンツの代替コンテンツを管理するのを支援する | assist (ママでOK) |
| 267 | B.2.4. アクセシブルなテンプレートでコンテンツ制作者を支援する | assist (ママでOK) |
| 268 | B.2.5. 事前に作成されたアクセシブルなコンテンツでコンテンツ制作者を支援する | assist (ママでOK) |
| 273 | B.3.1. アクセシビリティの問題のためのチェック時にコンテンツ制作者を支援する | assist (ママでOK) |
| 275 | B.3.2. アクセシビリティの問題を修正する際にコンテンツ制作者を支援する | assist (ママでOK) |
| 642 | ガイドライン A.3.3: (オーサリングツールのユーザインタフェース向け) コンテンツ制作者が発作を引き起こすような閃光を防ぐように支援する。 | help (ママでOK) |
| 1026 | ガイドライン B.2.3: コンテンツ制作者が非テキストコンテンツの代替コンテンツを管理するのを支援する。 | assist (ママでOK) |
| 1077 | ガイドライン B.2.4: アクセシブルなテンプレートでコンテンツ制作者を支援する。 | assist (ママでOK) |
| 1133 | ガイドライン B.2.5: 事前に作成されたアクセシブルなコンテンツでコンテンツ制作者を支援する。 | assist (ママでOK) |
| 1160 | ガイドライン B.3.1: アクセシビリティ問題のためのチェック時にコンテンツ制作者を支援する。 | assist (ママでOK) |
| 1220 | ガイドライン B.3.2: アクセシビリティ問題を修正する際にコンテンツ制作者を支援する。 | assist (ママでOK) |
| 1242 | アクセシブルなコンテンツを支援する機能  |  support (→用語集に合わせて「アクセシブルなコンテンツのサポート機能」に修正) |
| 1246 | アクセシブルなコンテンツを支援する機能  |  support (→用語集に合わせて「アクセシブルなコンテンツのサポート機能」に修正) |
| 1256 | アクセシブルなコンテンツを支援する機能  |  support (→用語集に合わせて「アクセシブルなコンテンツのサポート機能」に修正) |
| 1288 | アクセシブルなコンテンツを支援する機能  |  support (→用語集に合わせて「アクセシブルなコンテンツのサポート機能」に修正) |
| 1305 | アクセシブルなコンテンツを支援する機能  |  support (→用語集に合わせて「アクセシブルなコンテンツのサポート機能」に修正) |
| 1425 | 上記の適合表明の必須項目に加えて、コンテンツ制作者を支援するために追加情報を提供することを検討する。 | assist (ママでOK) |
| 1653 | オーサリングツールの使用を支援するための情報。 | support (→「オーサリングツールの使用をサポートするための情報。」に修正) |

**Comment by caztcha** [comment]
上の通り、「サポート」と「支援」について、改めてひととおり洗い出し、原文との対照 (および対応案) を検討しました。ほぼすべて、assistは支援、supportはサポートという訳し分けで成立します。

一点、表中に★をつけた箇所が迷いどころです。ガイドライン B.4.2. の「根拠 (Rationale)」の一節です。

- 日本語 https://waic.github.io/atag20-ja/#gl_b42
- 原文 https://www.w3.org/TR/ATAG20/#gl_b42

**Comment by bakera** [comment]
「サポートが必要である」を「サポートを必要とする」とすると違和感軽減されたりしないでしょうか。原文need動詞なので「必要とする」のほうが原文に近いように思います。

(もしかすると、原文の "accessible content production features" もミスではなく、同じように support かぶりを避けたくてこうしたのかもしれないですね。)

**Comment by caztcha** [comment]
@bakera  コメントありがとうございます。なるほどたしかに、原文では need が動詞ですね。

> 一部のコンテンツ制作者は、[アクセシブルなコンテンツのサポート機能]()をどのように使うか (例えば、テキストによる代替に対するプロンプトへの対応方法、アクセシビリティチェックツールの使用方法など) を判断するための、サポートを必要とする。

あるいは原文の support かぶりの回避を尊重して：

> 一部のコンテンツ制作者は、[アクセシブルなコンテンツを制作する機能]()をどのように使うか (例えば、テキストによる代替に対するプロンプトへの対応方法、アクセシビリティチェックツールの使用方法など) を判断するための、サポートを必要とする。

という具合でしょうか。

**Comment by caztcha** [comment]
いったんこれで PR 出しますね。 :)

**Comment by caztcha** [comment]
PR #144 にて対応中です。

**Comment by momdo** [comment]
マージ済みなのでcloseします。
