### ISSUE TITLE
「少なくとも同程度目立つ」 vs 「少なくとも顕在」

### ISSUE THREAD

**Issue by motchie** [waic/atag20-ja#82]
#40 より。
まずは該当箇所の列挙から

**Comment by motchie** [comment]
# 少なくとも同程度目立つ

1757:        <li><dfn><a name="def-At-Least-As-Prominent" id="def-At-Least-As-Prominent"></a>**少なくとも同程度目立つ**:</dfn> ATAG 2.0では次の場合に、<a class="termdef" href="#def-UI-Component" title="定義: ユーザインタフェースコンポーネント">ユーザインタフェースコンポーネント</a>Aが他のコンポーネントBよりも「**少なくとも同程度目立つ**」と考える。既定の状態からコンポーネントBが表示 (かつ有効) となる場合よりも同じかより少ない「オープニングアクション (Opening actions)」とともに、コンポーネントAが表示 (かつ有効) となった場合。<br />
1758:        <em> 注記 1:</em> コンテナが開いている場合は、コンテナ内の有効なコンポーネント (リスト内のアイテム、メニュー内のアイテム、ツールバーのボタン、ダイアログボックス内のすべてのコンポーネント) はすべて表示されているとみなされる (したがって「**少なくとも同程度目立つ**」)。コンテナーをスクロールして表示可能にしなければならない場合も同様で、これは様々なスクリーンの大きさと<a href="#def-Author" title="定義: コンテンツ制作者" class="termdef">コンテンツ制作者</a>の設定が一定期間表示されるコンポーネントに影響することを考慮している。<br />

# 少なくとも顕在

1286:        <p class="sc-title">全ての<a class="termdef" href="#def-Accessible-Content-Support-Features" title="definition: accessible content support features">アクセシブルなコンテンツのサポート機能</a>は、無効な<a href="#def-Markup" title="definition: markup" class="termdef">マークアップ</a>、シンタックスエラー、スペルミス又は文法エラーのいずれかに関連した機能として<a class="termdef" href="#def-At-Least-As-Prominent" title="definition: At Least As Prominent">**少なくとも顕在**</a>である。<span class="level">(<strong>レベル AA</strong>)</span> </p>

**Comment by bakera** [comment]
「顕在」は意味がわかりにくいので、「同程度目立つ」のほうにしたい気持ちです。
