### ISSUE TITLE
「順次キーボードアクセス」 vs 「連続したキーボードアクセス」

### ISSUE THREAD

**Issue by motchie** [waic/atag20-ja#83]
#40 より。
まずは該当箇所の列挙から。

**Comment by motchie** [comment]
# 順次キーボードアクセス

1795:    <dt><dfn><a name="def-Sequential-Keyboard-Access" id="def-Sequential-Keyboard-Access"></a>**順次キーボードアクセス**</dfn>

# 連続したキーボードアクセス

555:      <p class="sc-title"><a href="#def-Authoring-Tool-Interface" title="definition: authoring tool user interface" class="termdef">オーサリングツールのユーザインタフェース</a>は<a href="#def-Sequential-Keyboard-Access" title="definition: sequential keyboard navigation" class="termdef">**連続したキーボードアクセス**</a>により効率的にキーボードアクセスを可能にするメカニズムを取り入れている。<span class="level">（<strong>レベル AA</strong>）</span></p>

**Comment by momdo** [comment]
555行目がすでに「順次キーボードアクセス」に修正済みでは…？

**Comment by bakera** [comment]
WCAG 2.0の用語集では sequenceは「順序」「順」にしていますね。

正しく読む順序 (correct reading sequence)
順を追ってナビゲート (navigated sequentially)

「順次」の方で良いと思います。

**Comment by motchie** [comment]
ご指摘のとおり、 `master` ブランチに「連続したキーボードアクセス」が存在しなかったため、クローズします。
