### ISSUE TITLE
「デザイナ」 vs 「デザイナー」

### ISSUE THREAD

**Issue by motchie** [waic/atag20-ja#84]
#40 より
まずは該当箇所の列挙から。

**Comment by motchie** [comment]
# デザイナ

879:      <li><strong class="handle"><a name="part_b_applic_note_6" id="part_b_applic_note_6"></a>複数のオーサリングの役割:</strong> いくつかの<a class="termdef" href="#def-Authoring-Tool" title="definition: authoring tool">オーサリングツール</a>は、複数の<a href="#def-Author" title="definition: authors" class="termdef">コンテンツ制作者</a>の役割を含んでおり、それぞれの異なるビューとコンテンツの編集<a href="#def-Authoring-Permission" title="definition: author permission" class="termdef">権限</a>がある (例えば コンテンツ管理システムは、**デザイナ**、コンテンツ作成者及び品質保証者の役割を分けているかもしれないなど)。これらの場合、パート B の達成基準はオーサリングツール全体に適用され、特定のオーサリングの役割に提供されるビューには適用されない。<a class="termdef" href="#def-Accessible-Content-Support-Features" title="definition: accessible content support features">アクセシブルなコンテンツのサポート機能</a>は、役立つと思われる全てのオーサリングの役割で利用できるようにするべきである。</li>

# デザイナー
1524:	<dd><a href="#def-Authoring-Tool" title="定義: オーサリングツール" class="termdef">オーサリングツール</a>を使用して<a class="termdef" href="#def-Web-Content" title="定義: ウェブコンテンツ">ウェブコンテンツ</a>を作成又は編集する人。この用語は、コンテンツ制作者、**デザイナー**、プログラマー、出版者、テスター、といった役割をカバーする (<a href="#part_b_applic_note_6">パートB 適合適用性に関する注記: 6. 複数のオーサリングの役割</a>を参照)。いくつかのオーサリングツールでは、<a href="#def-Authoring-Permission" title="定義: 制作者権限" class="termdef">制作者権限</a>を管理することによって、誰がコンテンツ制作者になれるかを制御している。</dd>

**Comment by momdo** [comment]
[外来語（カタカナ）表記ガイドライン](https://www.jtca.org/standardization/katakana_guide_3_20171222.pdf)ですと、
designerはデザイナーとしていますが…。

**Comment by bakera** [comment]
デザイナーにしましょう (根拠のない決め)。
