### ISSUE TITLE
「ドキュメント」 vs 「ドキュメンテーション」

### ISSUE THREAD

**Issue by motchie** [waic/atag20-ja#85]
#40 より。
まずは該当箇所の列挙から。

**Comment by motchie** [comment]
# ドキュメント

281:                <li><a href="#gl_b42">B.4.2. アクセシブルなコンテンツの制作を促進する**ドキュメント**を確保する</a></li>
828:      <li class="sc-bullet"><strong class="handle">(a) **ドキュメント**で説明:</strong> 機能の使用方法はオーサリングツールの<a class="termdef" href="#def-Documentation" title="定義: ドキュメンテーション">ドキュメンテーション</a>に記載されている。または、</li>
844:      <h4 class="sc-title"><a id="sc_a422" name="sc_a422"> </a>A.4.2.2 すべての機能の**ドキュメント**化: </h4>
847:        <li class="sc-bullet"><strong class="handle">(a) **ドキュメント**で説明:</strong> 機能の使用方法はオーサリングツールの<a class="termdef" href="#def-Documentation" title="definition: documentation">ドキュメンテーション</a>に記載されている。又は、</li>
1294:    <h3 class="guideline"><a id="gl_b42" name="gl_b42"> </a> ガイドライン B.4.2: アクセシブルなコンテンツの制作を促進する**ドキュメント**を確保する。
1670:    <dt><a id="def-Document-Object" name="def-Document-Object"></a><dfn>**ドキュメント**オブジェクト (document object)</dfn></dt>
1671:    <dd><a href="#def-Non-Web-Based" title="定義: 非ウェブベースのオーサリングツール" class="termdef">非ウェブベースのオーサリングツール</a>又は<a href="#def-User-Agent" title="定義: ユーザエージェント" class="termdef">ユーザエージェント</a>による<a class="termdef" title="定義: ソース" href="#def-Instruction-Level">ソース</a>内のデータの内部表現。**ドキュメント**オブジェクトは<a href="#def-Assistive-Technology" title="定義: 支援技術" class="termdef">支援技術</a>とのやりとりを可能にする<a href="#def-Accessibility-Platform-Service" title="定義: プラットフォームのアクセシビリティサービス" class="termdef">プラットフォームのアクセシビリティサービス</a>の一部を形成する。 <a href="#def-Web-Based-UI" title="定義: ウェブベースのオーサリングツール" class="termdef">ウェブベースのオーサリングツール</a>は<a class="termdef" href="#def-User-Agent" title="定義: ユーザエージェント">ユーザエージェント</a>が管理する**ドキュメント**オブジェクトを利用してもよい。</dd>
1723:    <dd>アプリケーションと<a href="#def-Assistive-Technology" title="定義: 支援技術" class="termdef">支援技術</a>間のやりとりを提供するため特別に設計されたプログラムによるインタフェース (WindowsアプリケーションだとMSAA、IAccessible2、UI Automation、Mac OS XアプリケーションではAXAPI、GNOMEアプリケーションでは、GNOME Accessibility Toolkit API、JavaアプリケーションではJava Accessなど)。いくつかの<a href="#def-Platform" title="定義: プラットフォーム" class="termdef">プラットフォーム</a>では<a href="#def-Document-Object" title="定義: **ドキュメント**オブジェクト" class="termdef">**ドキュメント**オブジェクト</a>を実装することによって、従来のやりとりをさらに強化してもよい。</dd>
1733:        <li><dfn><a id="def-Accessible-Preauthored-Content" name="def-Accessible-Preauthored-Content"></a>アクセシブルなオーサリング済みコンテンツ (WCAG):</dfn> すでに<a class="termdef" href="#def-Accessible-Web-Content" title="定義: アクセシブルなウェブコンテンツ (WCAG)">アクセシブルなウェブコンテンツ (WCAG)</a>であるか、又は適切に空の**ドキュメント**に挿入されればアクセシブルになるだろう<a href="#def-Preauthored-Content" title="定義: オーサリング済みコンテンツ" class="termdef">オーサリング済みコンテンツ</a>のいずれか。<br />
1749:        <li>オーサリングツールと支援技術間のやり取り: <a href="#def-Non-Web-Based" title="定義: 非ウェブベースのユーザインタフェース" class="termdef">非ウェブベースのユーザインタフェース</a>の場合、<a class="termdef" href="#def-Accessibility-Platform-Service" title="定義: プラットフォームアクセシビリティサービス">プラットフォームアクセシビリティサービス</a>やAPI、また場合によっては**ドキュメント**オブジェクトモデルを利用することを意味する。<a class="termdef" href="#def-Web-Based-UI"  title="定義: ウェブベースのユーザインタフェース">ウェブベースのユーザインタフェース</a>の場合は、<a href="#def-User-Agent" title="定義: ユーザエージェント" class="termdef">ユーザエージェント</a>が (WAI-ARIAの使用などを通じて) 情報を伝えられることを保証することを意味する。
1762:        <em> 注記 4:</em> &quot;デフォルト状態&quot; は、開発者により設定されたオーサリングセッション開始時の<a href="#def-Authoring-Tool" title="definition: authoring tool" class="termdef">オーサリングツール</a>の状態である。 多くの**ドキュメント**オーサリングツールのデフォルト状態は<a href="#def-Editing-View" title="definition: editing views" class="termdef">編集ビュー</a>である。 </li>

# ドキュメンテーション

393:      <li><a name="part_a_applic_note_1" id="part_a_applic_note_1"></a><strong class="handle">「オーサリングツールのユーザインタフェース」の範囲:</strong> パート Aの達成基準は<a href="#conf-techs-produced">「含まれている」ウェブコンテンツ技術</a>の生成に関係している<a href="#def-Authoring-Tool-Interface" title="定義: オーサリングツールのユーザインタフェース" class="termdef">オーサリングツールのユーザインタフェース</a>のすべての部分に適用される。これは<a class="termdef" href="#def-Content-Being-Edited" title="定義: 編集中のウェブコンテンツ">編集中のウェブコンテンツ</a>の<a class="termdef" href="#def-View" title="定義: ビュー">ビュー</a>や、編集しているコンテンツの独立した機能を含む (例 : メニュー、ボタン、バー、ステータスバー、利用者の設定、<a class="termdef" href="#def-Documentation" title="定義: **ドキュメンテーション**">**ドキュメンテーション**</a>) 。</li>
401:      <li><a name="part_a_applic_note_5" id="part_a_applic_note_5"></a><strong class="handle">パート Aを満たすために提供されている機能のアクセシビリティ:</strong> パート Aの達成基準は、パー ト Aの達成基準を満たすために追加されたあらゆる機能 (例えば、**ドキュメンテーション**、検索機能) を含めた<a href="#def-Authoring-Tool-Interface" title="定義: オーサリングツールのユーザインタフェース" class="termdef">オーサリングツールのユーザインタフェース</a>全体に適用される。<a href="#gl_a37">ガイドライン A.3.7</a> の適当な達成基準を満たす限り、<a class="termdef" href="#def-Preview" title="定義: プレビュー">プレビュー</a>機能は唯一除外される。障害を持つ者を含むすべての開発者にとって、プレビュー機能が<span class="rationale"><a class="termdef" href="#def-End-Users" title="定義: エンドユーザ">エンドユーザ</a></span>の実際に使用するユーザエージェントの機能を正確に反映していることは有益であるため、プレビューは編集ビューとは扱いが異なる。</li>
821:    <p class="rationale">根拠: 一部の<a href="#def-Author" title="定義: コンテンツ制作者" class="termdef">コンテンツ制作者</a>は、<a href="#def-Documentation" title="定義: **ドキュメンテーション**" class="termdef">**ドキュメンテーション**</a>なしに<a href="#def-Authoring-Tool-Interface" title="定義: オーサリングツールのユーザインタフェース" class="termdef">オーサリングツールのユーザインタフェース</a>を理解したり操作することができない場合がある。</p>
828:      <li class="sc-bullet"><strong class="handle">(a) ドキュメントで説明:</strong> 機能の使用方法はオーサリングツールの<a class="termdef" href="#def-Documentation" title="定義: **ドキュメンテーション**">**ドキュメンテーション**</a>に記載されている。または、</li>
834:<li class="sc-note"><em class="note-handle">注記:</em> **ドキュメンテーション**のアクセシビリティについては<a href="#gl_a11">ガイドライン A.1.1</a>および<a href="#gl_a11">ガイドライン A.1.2</a>を参照。</li></ul>
847:        <li class="sc-bullet"><strong class="handle">(a) ドキュメントで説明:</strong> 機能の使用方法はオーサリングツールの<a class="termdef" href="#def-Documentation" title="definition: documentation">**ドキュメンテーション**</a>に記載されている。又は、</li>
853:      <li class="sc-note"><em class="note-handle">注記:</em> **ドキュメンテーション**のアクセシビリティについては<a href="#gl_a11">ガイドライン A.1.1</a>及び<a href="#gl_a11">ガイドライン A.1.2</a>を参照。</li></ul>
877:      <li><strong class="handle"><a name="part_b_applic_note_5" id="part_b_applic_note_5"></a>パート B を満たすために提供される機能のアクセシビリティ:</strong> <a href="#part_a">パート A</a> の達成基準は、パート B の達成基準を満たすために存在しなければならない機能を含んでいる<a href="#def-Authoring-Tool-Interface" title="definition: authoring tool user interface" class="termdef">オーサリングツールのユーザインタフェース</a>全体に適用される(例えば、チェックツール、リペアツール、チュートリアル、**ドキュメンテーション**など)。</li>
1303:      <p class="sc-title"><a class="termdef" href="#def-Documentation" title="定義: **ドキュメンテーション**">**ドキュメンテーション**</a>に含まれる実例の<a class="termdef" title="定義: 集まり" href="#def-Range">集まり</a>は、<a class="termdef" href="#def-Acc-Auth-Practice" title="定義: アクセシブルなオーサリングの慣例">アクセシブルなオーサリングの慣例 (WCAG)</a> (例えば、<a href="#def-Markup" title="定義: マークアップ" class="termdef">マークアップ</a>や、<a class="termdef" href="#def-WYSIWYG" title="定義: WYSIWYG">WYSIWYG</a> の<a href="#def-Editing-View" title="定義: 編集ビュー" class="termdef">編集ビュー</a>のスクリーンショットなど) を示す。<span class="level">(<strong>レベル A</strong> は WCAG 2.0 のレベル A の達成基準; <strong>レベル AA</strong> は WCAG 2.0 のレベル A と AA の達成基準; <strong>レベル AAA</strong> は WCAG 2.0 のすべての達成基準を満たす)</span></p>
1316:        <p class="sc-title">すべての<a class="termdef" href="#def-Accessible-Content-Support-Features" title="定義: アクセシブルなコンテンツを支援する機能">アクセシブルなコンテンツを支援する機能</a>の使用方法は<a class="termdef" href="#def-Documentation" title="定義: **ドキュメンテーション**">**ドキュメンテーション**</a>に記載されている。<span class="level">(<strong>レベル A</strong>)</span></p>
1335:      <p class="sc-title"> <a class="termdef" href="#def-Authoring-Tool" title="definition: authoring tool">オーサリングツール</a>の<a class="termdef" href="#def-Documentation" title="definition: documentation">**ドキュメンテーション**</a>は、<a class="termdef" href="#def-Accessible-Content-Support-Features" title="definition: accessible content support features">アクセシブルなコンテンツのサポート機能</a>を使用するための説明の索引を含む。<span class="level">(<strong>レベル AAA</strong>)</span></p>
1530:    <dd><a class="termdef" href="#def-Author" title="定義: コンテンツ制作者">コンテンツ制作者</a>が、<a class="termdef" href="#def-Authoring-Tool-Interface" title="定義: オーサリングツールのユーザインタフェース">オーサリングツールのユーザインタフェース</a>を用いて、<a class="termdef" href="#def-Web-Content" title="定義: ウェブコンテンツ">ウェブコンテンツ</a>を編集するアクションのこと (例えば、テキストのタイピング、削除、<a href="#def-Element" title="定義: 要素" class="termdef">要素</a>の挿入、<a href="#def-Template" title="定義: テンプレート" class="termdef">テンプレート</a>の適用、など)。その一方で、ほとんどのオーサリングツールのユーザインタフェースでは、コンテンツを編集しないアクション (例えば、保存、<a href="#def-Publishing" title="定義: 公開" class="termdef">公開</a>、プリファレンスの設定、<a href="#def-Documentation" title="定義: **ドキュメンテーション**" class="termdef">**ドキュメンテーション**</a>の表示) もまた可能である。
1667:    <dt><a id="def-Documentation" name="def-Documentation"></a><dfn>**ドキュメンテーション** (documentation)</dfn></dt>

**Comment by momdo** [comment]
そもそもATAG 2.0原文からして、documentとdocumentationが混在しているようです。統一する必要がどうか、というところからでしょうか？

**Comment by bakera** [comment]
documentation は定義された用語なので、

https://www.w3.org/TR/2015/REC-ATAG20-20150924/#def-Documentation
>Any information that supports the use of an authoring tool. This information may be provided electronically or otherwise and includes help, manuals, installation instructions, sample work flows, tutorials, etc.

これはわざと使い分けているのかもしれないですね。
一旦このままにしておきましょう。
