### ISSUE TITLE
「プロンプト」 vs 「要求」

### ISSUE THREAD

**Issue by motchie** [waic/atag20-ja#86]
#40 より。
まずは該当箇所の列挙から。

**Comment by motchie** [comment]
# プロンプト

1521:    <dd><a href="#def-Author" title="定義: コンテンツ制作者" class="termdef">コンテンツ制作者</a>のアクションによって<a class="termdef" href="#def-Authoring-Tool" title="定義: オーサリングツール">オーサリングツール</a>が<a class="termdef" href="#def-Accessible-Web-Content" title="定義: アクセシブルなウェブコンテンツ">アクセシブルなウェブコンテンツ (WCAG)</a> を生成できない場合。例えば、<a class="termdef" href="#def-Accessible-Content-Support-Features" title="定義: アクセシブルなコンテンツのサポート機能">アクセシブルなコンテンツのサポート機能</a>をオフにする、<a class="termdef" href="#def-Accessibility-Information" title="定義: アクセシビリティ情報">アクセシビリティ情報 (WCAG)</a> の<a href="#def-Prompt" title="定義: **プロンプト**" class="termdef">**プロンプト**</a>を無視する、誤ったアクセシビリティ情報 (WCAG) を**プロンプト**で提供する、オーサリングツールを改変する (スクリプトツールやマクロによって)、<a href="#def-Plugin" title="定義: プラグイン" class="termdef">プラグイン</a>をインストールする、などが含まれる。</dd>
1765:    <dt><a id="def-Prompt" name="def-Prompt"><dfn>**プロンプト**</dfn></a></dt>
1807:            <li>コンテンツ制作者が提供された指示に正しく従う（例えば、<a href="#def-Prompt" title="definition: prompt" class="termdef">**プロンプト**</a>に正しく応答し、強調表示されたプレースホルダを正しく置き換える）。そして</li>

# 要求

402:      <li><strong class="handle"><a name="part_a_applic_note_6" id="part_a_applic_note_6"></a>認識できないコンテンツ:</strong> 達成基準がオーサリングツールにウェブコンテンツをセマンティックな基準に沿って扱うことを**要求**する場合、達成基準はこれらのセマンティクスがプログラムによりエンコードされている場合にのみ適用される (例えば、画像を説明するテキストは、このロールがマークアップの中でエンコードされている場合<a class="termdef" href="#def-Text-Alternatives" title="非テキストコンテンツの代替テキスト">非テキストコンテンツの代替テキスト</a>として扱われる) 。</li>
905:       <li class="sc-bullet"><strong class="handle">(b) **要求**:</strong> 自動生成のプロセス中に、<span class="sc-title"><a href="#def-Author" title="定義: コンテンツ制作者" class="termdef">コンテンツ制作者</a></span>はいくつかの必要な<a class="termdef" href="#def-Accessibility-Information" title="定義: アクセシビリティ情報">アクセシビリティ情報 (WCAG)</a> が <a href="#def-Prompt" title="定義: **要求**" class="termdef">**要求**</a>される。または、</li>
907:       <li class="sc-bullet"><strong class="handle">(d) チェックの提案:</strong> 自動生成のプロセス後、オーサリングツールはコンテンツ制作者にアクセシビリティチェックを実行するように**要求**する。</li>
932:	  <li class="sc-bullet"><strong class="handle">(d) チェックの提案:</strong> オーサリングツールはコンテンツ制作者にアクセシビリティチェックを実行するように<a href="#def-Prompt" title="定義: **要求**" class="termdef">**要求**</a>する。</li></ul>
1299:      <p class="rationale">根拠: 一部の<a class="termdef" href="#def-Author" title="定義: コンテンツ制作者">コンテンツ制作者</a>は、<a class="termdef" href="#def-Accessible-Content-Support-Features" title="定義: アクセシブルなコンテンツを支援する機能">アクセシブルなコンテンツを支援する機能</a> (例えば、<span class="sc-bullet"><a class="termdef" href="#def-Text-Alternatives" title="非テキストコンテンツのテキストによる代替">テキストによる代替</a></span>に対する<a href="#def-Prompt" title="定義: **要求**" class="termdef">**要求**</a>への対応方法、アクセシビリティ<a href="#def-Checking" title="定義: チェック" class="termdef">チェック</a>ツールの使用方法など) を使う上でサポートが必要である。アクセシブルなオーサリングを習慣的な慣例として提示するか、あるいは少なくともアクセシブルではない慣例を提示しないことは、コンテンツ制作者に対してアクセシビリティの受け入れを促進するのに役立つ。</p>
1412:  <p>ATAG 2.0 は、ウェブコンテンツのライブオーサリング (例えば、いくつかのコラボレーションツール) を伴うワークフローをオーサリングツールに適用してもよい。 リアルタイム発行に固有の問題のため、これらのオーサリングツールの ATAG 2.0 <a href="#part_b">パート B</a> への適合は、ライブ<span class="sc"><a href="#def-Authoring-Session" title="definition: authoring session" class="termdef">オーサリングセッション</a></span>の前 (例えば、アクセシブルなスライドの準備におけるサポート)、間 (例えば、WCAG 2.0 がレベル AA で**要求**されるライブキャプション)、及び後 (例えば、リアルタイムで最初に公開されたプレゼンテーションのアーカイブにトランスクリプトを追加する機能など) のいくつかの組み合わせを伴ってもよい。詳細については、<a href="http://www.w3.org/TR/2015/NOTE-IMPLEMENTING-ATAG20-20150924/#realtime-production">ATAG 2.0 を実装する - 附録 E: ライブウェブコンテンツのためのオーサリングツール</a>を参照のこと。</p>
1532:        <li><dfn><a name="def-Reversible-Action" id="def-Reversible-Action"></a>可逆的なオーサリングアクション (reversible authoring action)</dfn>: <a class="termdef" href="#def-Authoring-Action" title="定義: オーサリングアクション">オーサリングアクション</a>のうち、<a class="termdef" href="#def-Author" title="定義: コンテンツ制作者">コンテンツ制作者</a>によるキャンセル**要求**があったときに<a href="#def-Authoring-Tool" title="定義: オーサリングツール" class="termdef">オーサリングツール</a>によって即座に完全に元に戻すことができるもの。キャンセル**要求**の例には、「キャンセル」「取り消し」「やり直し (「取り消し」を元に戻したいときに用いる)」「元に戻す」「ロールバック」などがある。<br />
1626:        <li><dfn><a name="def-Content-Auto-Gen" id="def-Content-Auto-Gen"></a>自動生成コンテンツ:</dfn> <a href="#def-Developer" title="定義: 開発者" class="termdef">開発者</a>がプログラミングした機能がすべての責任を負うウェブコンテンツ (例えば、コンテンツ制作者が新しい文書の開始を**要求**した際に出力するマークアップや、マークアップエラーの自動修正など)。</li>
1766:    <dd><a href="#def-Author" title="definition: authors" class="termdef">コンテンツ制作者</a>に判断又は情報の一部を求める<a href="#def-Authoring-Tool" title="definition: authoring tool" class="termdef">オーサリングツール</a>からのいくつかの**要求**。この用語は、すぐに対応する必要がある**要求**（例えばモーダルダイアログボックス）と緊急性の低い**要求**（例えばスペルミスのある単語に下線を引く）の両方を対象としている。</dd>
1791:    <dd><a href="#def-Author" title="definition: authors" class="termdef">コンテンツ制作者</a>が<a href="#def-Authoring-Tool" title="definition: authoring tool" class="termdef">オーサリングツール</a>で指定できる<a href="#def-Web-Content" title="definition: web content" class="termdef">ウェブコンテンツ</a>が特定のコンテンツ（要素、属性、ウィジェットなど）を含めなければならないか、又は含めてはならない場合。多くのオーサリングツールは、何らかの方法でオーサリングを制限することで、アクセシビリティに役立つ可能性（例えば非テキス​​トコンテンツの代替テキストが必要な場合）、もしくはアクセシビリティを損なう可能性（例えば代替テキストを定義するための属性が使えない場合）がある。対照的に、ウェブコンテンツのオーサリングを無制限に許可するオーサリングツール（例えば、多くの<a href="#def-Instruction-Level" title="definition: View - Source view" class="termdef">ソース編集ビュー</a>）は、特定のコンテンツが含まれるか含まれないかを**要求**しない。</dd>

**Comment by momdo** [comment]
promptとrequireとの単語について、差異を設けるかどうか、ということでしょうか…？

**Comment by bakera** [comment]
promptを要求と訳している箇所があるということですかね。
基本は「プロンプト」で良いと思います。
(逆にrequireは要求で良い)

**Comment by motchie** [comment]
# 402行目:
原文:
Unrecognizable content: When success criteria **require** authoring tools to treat web content according to semantic criteria, the success criteria only apply when these semantics are encoded programmatically (e.g. text describing an image can only be considered a text alternatives for non-text content when this role is encoded within markup).

訳:
認識できないコンテンツ: 達成基準がオーサリングツールに対し、セマンティックな基準に沿ってウェブコンテンツを扱うことを**要求**する場合、その達成基準は、これらのセマンティクスがプログラムによりエンコードされている場合にのみ適用される (例えば、画像を説明するテキストは、この役割がマークアップの中でエンコードされている場合にのみ、非テキストコンテンツに対するテキストによる代替として扱われる) 。

# 881行目:
原文:
Unrecognizable content: When success criteria **require** authoring tools to treat web content according to semantic criteria, the success criteria only apply when these semantics are encoded programmatically (e.g. text describing an image can only be considered a text alternatives for non-text content when this role is encoded within markup).

訳:
認識できないコンテンツ: 達成基準がオーサリングツールに対し、セマンティックな基準に沿ってウェブコンテンツを扱うことを**要求**する場合、その達成基準は、これらのセマンティクスがプログラムによりエンコードされている場合にのみ適用される (例えば、画像を説明するテキストは、この役割がマークアップの中でエンコードされている場合にのみ、非テキストコンテンツに対するテキストによる代替として扱われる) 。

# 906行目:
原文:
(b) **Prompting**: During the automatic generation process, authors are **prompted** for any required accessibility information (WCAG); or

訳:
(b) **要求**: 自動生成のプロセス中に、コンテンツ制作者はいくつかの必要なアクセシビリティ情報 (WCAG) が **要求**される。または、

# 906行目:
原文:
```<a href="#def-Prompt" title="definition: prompt" class="termdef">prompted</a>```

訳:
```<a href="#def-Prompt" title="定義: 要求" class="termdef">要求</a>される。```

# 908行目:
原文:
(d) Checking Suggested: After the automatic generation process, the authoring tool **prompts** authors to perform accessibility checking. 

訳:
(d) チェックの提案: 自動生成のプロセス後、オーサリングツールはコンテンツ制作者にアクセシビリティチェックを実行するように**要求**する。

# 933行目:
原文:
```After the transformation, the authoring tool <a href="#def-Prompt" title="definition: prompt" class="termdef">prompts</a> authors to perform accessibility checking.```

訳:
```オーサリングツールはコンテンツ制作者にアクセシビリティチェックを実行するように<a href="#def-Prompt" title="定義: 要求" class="termdef">要求</a>する。```

# 1300行目:
原文:
```
Some <a class="termdef" href="#def-Author" title="definition: author">authors</a> need support in determining how to use <a class="termdef" href="#def-Accessible-Content-Support-Features" title="definition: accessible content support features">accessible content production features</a> (e.g. how to respond to **<a href="#def-Prompt" title="definition: prompt" class="termdef">prompts</a>** for <span class="sc-bullet"><a class="termdef" href="#def-Text-Alternatives" title="text alternatives for non-text content">text alternatives</a></span>, how to use  accessibility <a href="#def-Checking" title="definition: checking" class="termdef">checking</a> tools).
```

訳:
```
一部の<a class="termdef" href="#def-Author" title="定義: コンテンツ制作者">コンテンツ制作者</a>は、<a class="termdef" href="#def-Accessible-Content-Support-Features" title="定義: アクセシブルなコンテンツを支援する機能">アクセシブルなコンテンツを支援する機能</a> (例えば、<span class="sc-bullet"><a class="termdef" href="#def-Text-Alternatives" title="非テキストコンテンツのテキストによる代替">テキストによる代替</a></span>に対する**<a href="#def-Prompt" title="定義: 要求" class="termdef">要求</a>**への対応方法、アクセシビリティ<a href="#def-Checking" title="定義: チェック" class="termdef">チェック</a>ツールの使用方法など) を使う上でサポートが必要である。
```

# 1413行目:
原文:
during (e.g. live captioning as WCAG 2.0 **requires** at Level AA)

訳:
間 (例えば、WCAG 2.0 がレベル AA で**要求**されるライブキャプション)

# 1533行目:
原文:
by the authoring tool upon a cancel **request** by an author.

訳:
オーサリングアクションのうち、コンテンツ制作者によるキャンセル**要求**があったときに

# 1533行目:
原文:
Examples of cancel **requests** include: "cancel", "undo", "redo" (when it used to reverse "undo"), "revert", and "roll-back"

訳:
キャンセル**要求**の例には、「キャンセル」「取り消し」「やり直し (「取り消し」を元に戻したいときに用いる)」「元に戻す」「ロールバック」などがある。

# 1627行目:
原文:
(e.g. what markup to output when an author **requests** to start a new document, automatically correcting markup errors).

訳:
(例えば、コンテンツ制作者が新しい文書の開始を**要求**した際に出力するマークアップや、マークアップエラーの自動修正など)。

# 1767行目:
原文:
**prompt**
Any authoring tool initiated **request** for a decision or piece of information from authors. The term covers both **requests** that must be responded to immediately (e.g. modal dialog boxes) as well as less urgent **requests** (e.g. underlining a misspelled word).

訳:
**プロンプト (prompt)**
コンテンツ制作者に判断又は情報の一部を求めるオーサリングツールからのいくつかの**要求**。この用語は、すぐに対応する必要がある**要求**（例えばモーダルダイアログボックス）と緊急性の低い**要求**（例えばスペルミスのある単語に下線を引く）の両方を対象としている。

# 1797行目:
原文:
In contrast, authoring tools that allow unrestricted web content authoring do not **require** any particular content to be included or not included (e.g. many source editing-views).

訳:
対照的に、ウェブコンテンツのオーサリングを無制限に許可するオーサリングツール（例えば、多くのソース編集ビュー）は、特定のコンテンツが含まれるか含まれないかを**要求**しない。

**Comment by momdo** [comment]
906行目が動詞だと思うんですけども、1767行目は名詞になってると思われ、これは…

**Comment by motchie** [comment]
もんどさんありがとうございます。
prompt を要求と訳している箇所を抜き出して、僕の理解が正しいか、訳語案も併記してみます。
いったん、動詞も名詞も両方あつかってみます。

# 906行目(1):
## 原文:
(b) **Prompting**: During the automatic generation process, authors are **<a href="#def-Prompt" title="definition: prompt" class="termdef">prompted</a>** for any required accessibility information (WCAG); or
## 訳:
(b) **要求**: 自動生成のプロセス中に、コンテンツ制作者はいくつかの必要なアクセシビリティ情報 (WCAG) が **<a href="#def-Prompt" title="定義: 要求" class="termdef">要求</a>される。** される。または、
## 修正訳案:
(b) **プロンプト**: 自動生成のプロセス中に、コンテンツ制作者はいくつかの必要なアクセシビリティ情報 (WCAG) が **<a href="#def-Prompt" title="定義: プロンプト" class="termdef">プロンプト</a>される。** される。または、

# 908行目:
## 原文:
(d) Checking Suggested: After the automatic generation process, the authoring tool **prompts** authors to perform accessibility checking. 
## 訳:
(d) チェックの提案: 自動生成のプロセス後、オーサリングツールはコンテンツ制作者にアクセシビリティチェックを実行するように**プロンプトする**。
## 修正訳案:
(d) チェックの提案: 自動生成のプロセス後、オーサリングツールはコンテンツ制作者にアクセシビリティチェックを実行するように**プロンプトする**。

# 933行目:
## 原文:
```After the transformation, the authoring tool <a href="#def-Prompt" title="definition: prompt" class="termdef">prompts</a> authors to perform accessibility checking.```
## 訳:
```オーサリングツールはコンテンツ制作者にアクセシビリティチェックを実行するように<a href="#def-Prompt" title="定義: 要求" class="termdef">要求</a>する。```
## 修正訳案:
```オーサリングツールはコンテンツ制作者にアクセシビリティチェックを実行するように<a href="#def-Prompt" title="定義: プロンプト" class="termdef">プロンプト</a>する。```

# 1300行目:
## 原文:
```Some authors need support in determining how to use accessible content production features (e.g. how to respond to **<a href="#def-Prompt" title="definition: prompt" class="termdef">prompts</a>** for text alternatives, how to use  accessibility checking tools).```
## 訳:
```一部のコンテンツ制作者は、アクセシブルなコンテンツを支援する機能(例えば、テキストによる代替に対する**<a href="#def-Prompt" title="定義: 要求" class="termdef">要求</a>**への対応方法、アクセシビリティチェックツールの使用方法など) を使う上でサポートが必要である。```
## 修正訳案:
```一部のコンテンツ制作者は、アクセシブルなコンテンツを支援する機能(例えば、テキストによる代替に対する**<a href="#def-Prompt" title="定義: プロンプト" class="termdef">プロンプト</a>**への対応方法、アクセシビリティチェックツールの使用方法など) を使う上でサポートが必要である。```

**Comment by momdo** [comment]
誤ってissueをcloseしてしまいましたが（ReOpenしなおしましたが）そこは目を瞑ってもらって、やはり「プロンプトする」というのは日本語としてちょっと難があるのかなと…（じゃあどうすればいいのかの答えについて、今は持ち合わせてないのですが）

**Comment by motchie** [comment]
> （じゃあどうすればいいのかの答えについて、今は持ち合わせてないのですが）

そこなんですよね。「入力を促す」とかにすると、用語集の方が苦しくなりますし…。

**Comment by momdo** [comment]
> 「入力を促す」とかにすると、用語集の方が苦しくなりますし…。

持田さんご指摘のように、和語表現（≒促す）だと苦しいですが、（要求のような）漢語表現にするとかなり楽になるかなと。

類語辞典で<a href="https://thesaurus.weblio.jp/content/%E4%BF%83%E3%81%99">促す</a>を引いてみると、「要求」も見えますが、「催促」というのも見えます。このissueに書かれているものを単純に置換すると次のような感じになります（まあ、原文と比較して訳を直したほうがよいだろうものもありますが）

----
#### 906:
(b) **催促**: 自動生成のプロセス中に、コンテンツ制作者はいくつかの必要なアクセシビリティ情報 (WCAG) が**催促**される。または、

#### 933:
(d) チェックの提案: 自動生成のプロセス後、オーサリングツールはコンテンツ制作者にアクセシビリティチェックを実行するように**催促**する。

#### 1300:
一部のコンテンツ制作者は、アクセシブルなコンテンツを支援する機能(例えば、テキストによる代替に対する**催促**への対応方法、アクセシビリティチェックツールの使用方法など) を使う上でサポートが必要である。

#### 1521:
コンテンツ制作者のアクションによってオーサリングツールがアクセシブルなウェブコンテンツ (WCAG) を生成できない場合。例えば、アクセシブルなコンテンツのサポート機能をオフにする、アクセシビリティ情報 (WCAG) の**催促**を無視する、誤ったアクセシビリティ情報 (WCAG) を**催促**で提供する、オーサリングツールを改変する (スクリプトツールやマクロによって)、プラグインをインストールする、などが含まれる。

#### 1765:
**催促** (prompt)

#### 1807:
コンテンツ制作者が提供された指示に正しく従う（例えば、**催促**に正しく応答し、強調表示されたプレースホルダを正しく置き換える）。そして

----
と、致命的な破綻は避けられているかなという気はしますが、どんなもんでしょうか…

**Comment by motchie** [comment]
- 名詞形: プロンプト
- 動詞形: 促す(prompt)

**Comment by momdo** [comment]
#134でマージいただいたので閉じます。
