### ISSUE TITLE
「二つ」 vs 「2つ」

### ISSUE THREAD

**Issue by motchie** [waic/atag20-ja#88]
#40 より。
まずは該当箇所の列挙から。

**Comment by motchie** [comment]
# 二つ

1374:    <li>**二つ**目は、「 WCAG 2.0 への適合は、たとえそれが最高レベル ( つまりレベル AAA )であっても、『障害のすべてのタイプ、程度、又はこれらの組み合わせの人々がアクセシブル』なコンテンツを作成しないことがありうる」。 
1745:    <dd><a href="#def-Assistive-Technology" title="定義: 支援技術" class="termdef">支援技術</a>を含む異なるソフトウェアが異なる方式で情報を抽出したり提示できるようにエンコードされた情報。ATAG 2.0ではこの用語を次の**二つ**の文脈で利用する:<br />

# 2つ

325:  <p>オーサリングツールのアクセシビリティは、障害を持つ重複する**2つ**の利用者グループのニーズに対応する:</p>
332:  <p>この**2つ**の利用者のニーズを満たすための要件は、ガイドライン内で分かりやすくするために分離されているが、利用者作成コンテンツの流行において、実際には相互に深く関連していることに注意すべきである。例えば、利用者がオンラインフォーラムに参加する場合、利用者はしばしばコンテンツを作成し、他の利用者によって作成されたコンテンツと組み合わされる。オーサリングユーザインタフェース、または他のフォーラム利用者によって作成されたコンテンツのアクセシビリティの問題は、フォーラムの全体的なアクセシビリティを低下させる。</p>
353:    <li><strong>パート：</strong> ATAG 2.0は**2つ**のパートに分かれており、それぞれがオーサリングツールに関する重要なアクセシビリティの側面を反映している。<a href="#part_a">パートA</a>の内容は、障害のあるコンテンツ制作者に対する<a class="termdef" title="定義: オーサリングツールのユーザインタフェース" href="#def-Authoring-Tool-Interface">オーサリングツールのユーザインタフェース</a>のアクセシビリティに関することである。<a href="#part_b">パートB</a>の内容は、（障害者に限らない）コンテンツ制作者が、障害を持つ<a class="termdef" href="#def-End-Users" title="定義: エンドユーザ">エンドユーザ</a>にとってよりアクセシブルな<a class="termdef" href="#def-Web-Content" title="定義: ウェブコンテンツ">ウェブコンテンツ</a>作成ができるようにするための、オーサリングツールによるサポートに関することである。どちらのパートも、そのパート内のすべての達成基準に適用される<a class="termdef" href="#def-Normative" title="定義: 規定">規定</a>の「適合適用性に関する注記」が含まれる：<a href="#part_a_applic_notes">パートAの適合適用性に関する注記</a> 及び <a href="#part_b_applic_notes">パートBの適合適用性に関する注記</a>。</li>
1371: また定義には、**2つ**の注釈が含まれている: </p>
1387:  <p>適合には**2つ**の種類があり、それぞれに3つのレベルがある:</p>
1494:        <li><dfn><a id="def-Text-Alternatives" name="def-Text-Alternatives"></a>非テキストコンテンツに対するテキストによる代替:</dfn> 非テキストコンテンツに<a href="#def-Associated-Alternative-Content" title="定義: プログラムで関連付けられる" class="termdef">プログラムで関連付けられる</a>テキスト、又は非テキストコンテンツにプログラムで関連付けられるテキストから参照されるテキスト。例えば、ある図表の画像には、テキストによる代替が**2つ**ある: 図表の後の段落に記述される説明と、図表に対する短いテキストによる代替でその後に説明が続く旨を示すもの、である。</li>

**Comment by momdo** [comment]
https://github.com/waic/atag20-ja/issues/87#issuecomment-456753535 も参照。
