### ISSUE TITLE
「アクセシビリティ サポーテッド」 vs 「アクセスサポーティッド」

### ISSUE THREAD

**Issue by motchie** [waic/atag20-ja#89]
#40 より。
まずは該当箇所の列挙から。

**Comment by motchie** [comment]
# アクセシビリティ サポーテッド

336:    <li>「<a class="termdef" href="#def-Accessible-Web-Content" title="定義: アクセシブルなウェブコンテンツ">アクセシブルなウェブコンテンツ (WCAG)</a>」という用語と、「<a href="#def-Accessible-Template" title="定義: アクセシブルなテンプレート" class="termdef">アクセシブルなテンプレート (WCAG)</a>」などの関連用語は、 ATAG 2.0 では、レベルA、AAまたはAAAのいずれかで「 <a href="#conf-rel-wcag">WCAG 2.0</a> に適合するコンテンツ」を指すために使用され、WCAG 2.0 の達成基準を満たすために依存している<a href="#def-Web-Content-Technology" title="定義: 技術（ウェブコンテンツ）" class="termdef">ウェブコンテンツ技術</a>がいずれも**アクセシビリティ サポーテッド**であることを前提としている。 WCAG2.0 の最高レベル (AAA) で適合しているコンテンツでさえも、「すべての種類、程度あるいは組合せの障害者にとってアクセシブル」ではないという WCAG2.0 における注釈をこの用語の定義は反映している。詳細については、「<a href="#conf-rel-wcag">ウェブコンテンツアクセシビリティガイドライン（WCAG）2.0との関係</a>」を参照。</li>
1369:「アクセシブルなコンテンツ」の定義は、WCAG 2.0 にレベル A、AA、又は AAA のいずれかで適合するコンテンツであり、WCAG 2.0 の達成基準を満たすために必要な任意のウェブコンテンツ技術が**アクセシビリティ サポーテッド**であることを前提としている。
1373:    <li>一つ目は、「**アクセシビリティ サポーテッド**でない技術がある場合、コンテンツは WCAG2.0 に適合しておらず、障害当事者の利用者の１つ以上のグループはコンテンツにアクセスするのが困難であろう」。</li>
1379:  <h5><a id="conf-note" name="conf-note"></a>「技術の**アクセシビリティ サポーテッド**な使用方法」についての注記:</h5>
1380:  <p>「 WCAG 2.0 の達成基準を満たすために、**アクセシビリティ サポーテッド**な方法のみに依存する。アクセスサポーティッドでない方法で提供される任意の情報や機能は、アクセスサポーティッドな方法でも利用可能である。」という要件は、WCAG 2.0 への適合の一部である。広義には以下の場合、WCAG 2.0 はウェブコンテンツ技術を<em>**アクセシビリティ サポーテッド**</em>であるとみなす。 ( 1 ) <a href="#def-Web-Content-Technology" title="定義: 技術 ( ウェブコンテンツ ) " class="termdef">ウェブコンテンツ技術</a>が使用される方法が、ユーザの<a class="termdef" href="#def-Assistive-Technology" title="定義: 支援技術">支援技術</a>によりサポートされており、かつ ( 2 ) ウェブコンテンツ技術が、エンドユーザが利用できる**アクセシビリティ サポーテッド**な<a class="termdef" href="#def-User-Agent" title="定義: ユーザエージェント">ユーザエージェント</a>を有する場合。</p>
1383:    <p><strong>ATAG 2.0 は、**アクセシビリティ サポーテッド**要件を含んでいない。その結果、ATAG 2.0 の達成基準は WCAG 2.0「適合」を参照しておらず、代わりに「WCAG 2.0 達成基準への適合」を参照している。</strong></p>
1385:  <p>ひとたびオーサリングツールがインストールされ使用されると、WCAG 2.0**アクセシビリティ サポーテッド**要件が満たされているかどうかを含め、オーサリングツールが制作する<a class="termdef" href="#def-Web-Content" title="定義: ウェブコンテンツ">ウェブコンテンツ</a>の WCAG 2.0 適合評価が可能であろう。しかし、この WCAG 2.0 適合評価は、オーサリングツールの ATAG 2.0 適合とは完全に独立しているだろう。</p>

# アクセスサポーティッド

1380:  <p>「 WCAG 2.0 の達成基準を満たすために、アクセシビリティ サポーテッドな方法のみに依存する。**アクセスサポーティッド**でない方法で提供される任意の情報や機能は、**アクセスサポーティッド**な方法でも利用可能である。」という要件は、WCAG 2.0 への適合の一部である。広義には以下の場合、WCAG 2.0 はウェブコンテンツ技術を<em>アクセシビリティ サポーテッド</em>であるとみなす。 ( 1 ) <a href="#def-Web-Content-Technology" title="定義: 技術 ( ウェブコンテンツ ) " class="termdef">ウェブコンテンツ技術</a>が使用される方法が、ユーザの<a class="termdef" href="#def-Assistive-Technology" title="定義: 支援技術">支援技術</a>によりサポートされており、かつ ( 2 ) ウェブコンテンツ技術が、エンドユーザが利用できるアクセシビリティ サポーテッドな<a class="termdef" href="#def-User-Agent" title="定義: ユーザエージェント">ユーザエージェント</a>を有する場合。</p>

**Comment by momdo** [comment]
WCAG 2.0のとおり、accessibility supported（ハイフンがあろうとなかろうと）はすべて「アクセシビリティ サポーテッド」とします。
