### ISSUE TITLE
「プラットフォームアクセシビリティサービス」 vs 「プラットフォームのアクセシビリティサービス」

### ISSUE THREAD

**Issue by motchie** [waic/atag20-ja#90]
#40 より。
まずは該当箇所の列挙から

**Comment by motchie** [comment]
# 「プラットフォームアクセシビリティサービス」

429:    <p class="rationale">根拠: <a class="termdef" href="#def-Authoring-Tool" title="定義: オーサリングツール">オーサリングツール</a>（またはオーサリングツールの一部）が<a class="termdef" href="#def-Non-Web-Based" title="定義: オーサリングツールのユーザインタフェース（非ウェブベース）">非ウェブベース</a>の場合、既存の<a href="#def-Platform" title="定義: プラットフォーム" class="termdef">プラットフォーム</a>のアクセシビリティガイドラインに従い、また<a class="termdef" href="#def-Accessibility-Platform-Service" title="定義: アクセシビリティプラットフォームアーキテクチャ">**プラットフォームアクセシビリティサービス**</a>との通信を実装することにより、<a class="termdef" href="#def-Assistive-Technology" title="定義: 支援技術">支援技術</a>を使用する人を含む、すべての<a href="#def-Author" title="定義: コンテンツ制作者" class="termdef">コンテンツ制作者</a>によるアクセスが容易になる。</p>
446:      <h4 class="sc-title"><a id="sc_a122" name="sc_a122"></a>A.1.2.2 **プラットフォームアクセシビリティサービス**: </h4>
447:      <p class="sc-title"><a class="termdef" href="#def-Authoring-Tool" title="定義: オーサリングツール">オーサリングツール</a>に<a class="termdef" href="#def-Non-Web-Based" title="定義: オーサリングツールのユーザインタフェース（非ウェブベース）">非ウェブベースのユーザインタフェース</a>が含まれている場合、その非ウェブベースのユーザインタフェースは使用している<a class="termdef" href="#def-Accessibility-Platform-Service" title="定義: アクセシビリティプラットフォームアーキテクチャ">**プラットフォームアクセシビリティサービス**</a>を通じてアクセシビリティ情報を公開する。<span class="level">（<strong>レベル A</strong>）</span></p>
449:    <li class="sc-note"><em class="note-handle">注記: </em><em class="note-handle"></em>任意の<a href="#conf-explanation-results">適合表明の結果の説明</a>には、実装された**プラットフォームアクセシビリティサービス**を記録するべきである。</li>
831:      <li class="sc-bullet"><strong class="handle">(d) コンテンツ制作者によって使用されない:</strong> 機能は<a href="#def-Author" title="定義: コンテンツ制作者" class="termdef">コンテンツ制作者</a>が直接使用しない ( 例えば情報を<a class="termdef" href="#def-Accessibility-Platform-Service" title="定義: アクセシビリティプラットフォームアーキテクチャ">**プラットフォームアクセシビリティサービス**</a>に渡すなど ) 。</li>
850:        <li class="sc-bullet"><strong class="handle">(d) コンテンツ制作者によって使用されない:</strong> 機能は<a href="#def-Author" title="definition: authors" class="termdef">コンテンツ制作者</a>が直接使用しない (例えば、情報を<a class="termdef" href="#def-Accessibility-Platform-Service" title="definition: accessibility platform architecture">**プラットフォームアクセシビリティサービス**</a>に渡す).</li>
1432:        <li> <a name="conf-not-user-agents" id="conf-not-user-agents"></a>(<a class="termdef" href="#def-Non-Web-Based" title="definition: authoring tool user interface (non-Web-Based)">非ウェブベースのオーサリングツールのユーザインタフェース</a>を評価するために使用される) <strong><a href="#def-User-Agent" title="definition: user agent" class="termdef">ユーザエージェント</a>ではないプラットフォーム</strong>の場合: プラットフォーム (例えばデスクトップオペレーティングシステム、モバイルオペレーティングシステム、クロス OS 環境) の名前及びバージョン情報並びに採用された<a href="#def-Accessibility-Platform-Service" title="definition: platform accessibility architectur" class="termdef">**プラットフォームアクセシビリティサービス**</a>の名前及びバージョンを提供する。</li>
1719:      <em> 注記 1:</em> 多くのプラットフォームはプラットフォーム上で動作するアプリケーションと支援技術の間を<a class="termdef" href="#def-Accessibility-Platform-Service" title="定義: **プラットフォームアクセシビリティサービス**">**プラットフォームアクセシビリティサービス**</a>を介して仲介する。<br />
1722:    <dt><dfn><a id="def-Accessibility-Platform-Service" name="def-Accessibility-Platform-Service"></a>**プラットフォームアクセシビリティサービス** (platform accessibility service)</dfn></dt>
1749:        <li>オーサリングツールと支援技術間のやり取り: <a href="#def-Non-Web-Based" title="定義: 非ウェブベースのユーザインタフェース" class="termdef">非ウェブベースのユーザインタフェース</a>の場合、<a class="termdef" href="#def-Accessibility-Platform-Service" title="定義: **プラットフォームアクセシビリティサービス**">**プラットフォームアクセシビリティサービス**</a>やAPI、また場合によってはドキュメントオブジェクトモデルを利用することを意味する。<a class="termdef" href="#def-Web-Based-UI"  title="定義: ウェブベースのユーザインタフェース">ウェブベースのユーザインタフェース</a>の場合は、<a href="#def-User-Agent" title="定義: ユーザエージェント" class="termdef">ユーザエージェント</a>が (WAI-ARIAの使用などを通じて) 情報を伝えられることを保証することを意味する。

# プラットフォームのアクセシビリティサービス

1405:  <p><a class="termdef" href="#def-Authoring-Tool" title="definition: authoring tool">オーサリングツール</a>が (例えば、<a class="termdef" href="#def-Accessibility-Platform-Service" title="definition: accessibility platform architecture">**プラットフォームのアクセシビリティサービス**</a>を欠いているなど) <a class="termdef" href="#def-Platform" title="definition: platform">プラットフォーム</a>固有の制限のために一つ以上の達成基準を満たすことができない場合、この適合オプションが選択されてもよい。(任意の) 適合表明の結果の説明は、どのプラットフォームの機能が欠けているかを説明することが望ましい。 </p>
1671:    <dd><a href="#def-Non-Web-Based" title="定義: 非ウェブベースのオーサリングツール" class="termdef">非ウェブベースのオーサリングツール</a>又は<a href="#def-User-Agent" title="定義: ユーザエージェント" class="termdef">ユーザエージェント</a>による<a class="termdef" title="定義: ソース" href="#def-Instruction-Level">ソース</a>内のデータの内部表現。ドキュメントオブジェクトは<a href="#def-Assistive-Technology" title="定義: 支援技術" class="termdef">支援技術</a>とのやりとりを可能にする<a href="#def-Accessibility-Platform-Service" title="定義: **プラットフォームのアクセシビリティサービス**" class="termdef">**プラットフォームのアクセシビリティサービス**</a>の一部を形成する。 <a href="#def-Web-Based-UI" title="定義: ウェブベースのオーサリングツール" class="termdef">ウェブベースのオーサリングツール</a>は<a class="termdef" href="#def-User-Agent" title="定義: ユーザエージェント">ユーザエージェント</a>が管理するドキュメントオブジェクトを利用してもよい。</dd>

**Comment by momdo** [comment]
ATAG 2.0の用語集で用語として存在するので「の」がない方が美しいのでは？
まあ長いので、「プラットフォーム アクセシビリティサービス」とスペースを入れると読みやすいかもしれません。
